<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE set [
	  <!ELEMENT set (pdf*)>
	  <!ATTLIST set
		    scale CDATA #REQUIRED
		    name  CDATA #REQUIRED >
	  <!ELEMENT pdf (parameter*) >
	  <!ATTLIST pdf
		    name CDATA #REQUIRED
		    pid  ID    #IMPLIED
		    src  IDREF #IMPLIED
		    dfav IDREF #IMPLIED
		    fav  IDREF #IMPLIED
		    >
	  <!ELEMENT parameter (ems*) >
	  <!ATTLIST parameter
		    index  CDATA #REQUIRED
		    srcid  CDATA #IMPLIED
		    name   CDATA #IMPLIED
		    value  CDATA #REQUIRED
		    error  CDATA #IMPLIED
		    state  (fixed|free|add|multi) #REQUIRED
		    upper  CDATA #IMPLIED
		    lower  CDATA #IMPLIED
		    emid   CDATA #IMPLIED
		    >
	  <!ELEMENT ems EMPTY >
	  <!ATTLIST ems
		    emid   CDATA  #REQUIRED
		    value  CDATA  #REQUIRED
		    >
	  ]>

<set scale="1.0" name="Fragmentation">
  
  <pdf name="u" pid="FAVOR">
    <parameter index="0" name="N" value="0.0740" error="0.0268" state="fixed" upper="1" lower="0"></parameter>
    <parameter index="1" name="a" value="-.630" error="0.629" state="fixed" upper="100" lower="-2"></parameter>
    <parameter index="2" name="b" value="1.310" error="0.772" state="fixed" upper="100" lower="-100"></parameter>
  </pdf>
  
  <pdf name="s-bar" pid="s-bar">
    <parameter index="0" name="N" value="0.0878" error="0.0506" state="fixed" upper="1" lower="0"></parameter>
    <parameter index="1" name="a" value="2.000" error="2.913" state="fixed" upper="100" lower="-2"></parameter>
    <parameter index="2" name="b" value="2.800" error="1.313" state="fixed" upper="100" lower="-100"></parameter>
  </pdf>
  
  <pdf name="u-bar" pid="DISFAVOR">
    <parameter index="0" name="N" value="0.0255" error="0.0173" state="fixed" upper="1" lower="0"></parameter>
    <parameter index="1" name="a" value="1.012" error="0.939" state="fixed" upper="100" lower="-2"></parameter>
    <parameter index="2" name="b" value="8.000" error="3.715" state="fixed" upper="100" lower="-100"></parameter>
  </pdf>
  <pdf name="d"     src="DISFAVOR"></pdf>
  <pdf name="d-bar" src="DISFAVOR"></pdf>
  <pdf name="s"     src="DISFAVOR"></pdf>
  
  <pdf name="c" pid="CHARM">
    <parameter index="0" name="N" value="0.0583" error="0.0052" state="fixed" upper="1" lower="0"></parameter>
    <parameter index="1" name="a" value="0.527" error="0.228" state="fixed" upper="100" lower="-2"></parameter>
    <parameter index="2" name="b" value="5.866" error="0.636" state="fixed" upper="100" lower="-100"></parameter>
  </pdf>
  <pdf name="c-bar" src="CHARM"></pdf>
  
  <pdf name="b" pid="BOTTOM">
    <parameter index="0" name="N" value="0.0522" error="0.0024" state="fixed" upper="1" lower="0"></parameter>
    <parameter index="1" name="a" value="0.247" error="0.126" state="fixed" upper="100" lower="-2"></parameter>
    <parameter index="2" name="b" value="11.212" error="0.721" state="fixed" upper="100" lower="-100"></parameter>
  </pdf>
  <pdf name="b-bar" src="BOTTOM"></pdf>
  
  <pdf name="g" dfav="FAVOR" fav="DISFAVOR">
    <parameter index="0" name="N" value="0.0705" error="0.0099" state="fixed" upper="0" lower="0"></parameter>
    <parameter index="1" name="a" value="5.000" error="0.000" state="fixed" upper="100" lower="-2"></parameter>
    <parameter index="2" name="b" value="0.810" error="0.239" state="fixed" upper="100" lower="-100"></parameter>
  </pdf>
  
</set>
