<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE set [
	  <!ELEMENT set (pdf*)>
	  <!ATTLIST set   scale CDATA #REQUIRED
		    name  CDATA #REQUIRED >
	  
	  <!ELEMENT pdf (parameter*) >
	  <!ATTLIST pdf  
		    name  CDATA  #REQUIRED
		    pid   ID     #IMPLIED
		    src   IDREF  #IMPLIED
		    dfav  IDREF  #IMPLIED
		    fav   IDREF  #IMPLIED
		    >
	  
	  <!ELEMENT parameter EMPTY >
	  <!ATTLIST parameter 
		    index  CDATA        #REQUIRED
		    name   CDATA        #IMPLIED
		    value  CDATA        #REQUIRED
		    error  CDATA        #IMPLIED
		    state  (fixed|free) #REQUIRED
		    upper  CDATA        #IMPLIED
		    lower  CDATA        #IMPLIED
		    >
	  
	  ]>		      

<set scale="0.26" name="Fragmentation">
  
  <pdf name="s-bar" pid="s-bar" >
    <parameter index="0" name="eta" value="0.213" error="0.1" state="free" />
    <parameter index="1" name="a"   value="0.617" error="0.1" state="free" lower="-2" />
    <parameter index="2" name="b"   value="0.744" error="0.1" state="free" />
  </pdf>
  
  <pdf name="u"     pid="u"     dfav="s-bar" ></pdf>
  
  <pdf name="d"     pid="d"     dfav="u" ></pdf>
  <pdf name="d-bar" src="d"  ></pdf>
  <pdf name="u-bar" src="d" ></pdf>
  <pdf name="s"     src="d" ></pdf>
  
  <pdf name="gluon" dfav="u" fav="d" >
    <parameter index="1" name="a"   value="8.132" error="0.1" state="free" lower="-2" />
    <parameter index="2" name="b"   value="5.776" error="0.1" state="free" />
  </pdf>
  
  <pdf name="c" pid="CHARM" >
    <parameter index="0" name="eta" value="0.085" error="0.1" state="free" upper="1.0" lower="0.0" />
    <parameter index="1" name="a"   value="1.419" error="0.1" state="free" lower="-2.0" />
    <parameter index="2" name="b"   value="6.171" error="0.1" state="free" />
  </pdf>
  
  <pdf name="b" pid="BOTTOM" >
    <parameter index="0" name="eta" value="0.062"  error="0.1" state="free" upper="1.0" lower="0.0" />
    <parameter index="1" name="a"   value="0.191" error="0.1" state="free" lower="-2.0" />
    <parameter index="2" name="b"   value="8.934"  error="0.1" state="free" />
  </pdf>
  
  <pdf name="c-bar" src="CHARM" ></pdf>
  <pdf name="b-bar" src="BOTTOM"></pdf>
  
</set>
