<?xml version="1.0" encoding="utf-8" ?>
<!--
  $Id: KretzerLO_R.xml,v 1.1 2008/11/07 05:39:45 imazu Exp $
  
  This is an example of initial distributions for fragmentation function.
  It should be read by 
  Fragmentation::ConfigFF, Fragmentation::ConfigFFK and
  polFrag::ConfigFF class objects.
  
  Not it is implemented to copy contents of the existing pdf to another
  pdf, with attribute src.
  
  Author:  $Author: imazu $
  Date:    $Date: 2008/11/07 05:39:45 $
  Version: $Revision: 1.1 $
  
  *****************  caution  *****************
  ** Lower limit for parameter a ( power of z ).
  Usually, for hadron production crossection 
  the offset on the real axis for Mellin inversion is set to 2.0.
  In that case, a must be grater than -2.0.
  
  -->
<!DOCTYPE set [
	  <!ELEMENT set (pdf*)>
	  <!ATTLIST set  
		    scale CDATA #REQUIRED
		    name  CDATA #REQUIRED >
	  
	  <!ELEMENT pdf (parameter*) >
	  <!ATTLIST pdf  
		    name  CDATA  #REQUIRED
		    pid   ID     #IMPLIED
		    src   IDREF  #IMPLIED
		    dfav  IDREF  #IMPLIED
		    >
	  
	  <!ELEMENT parameter (ems*) >
	  <!ATTLIST parameter 
		    index  CDATA        #REQUIRED
		    name   CDATA        #IMPLIED
		    value  CDATA        #REQUIRED
		    error  CDATA        #IMPLIED
		    state  (fixed|free) #REQUIRED
		    upper  CDATA        #IMPLIED
		    lower  CDATA        #IMPLIED
		    emid   CDATA        #IMPLIED
		    >

	  <!ELEMENT ems EMPTY >
	  <!ATTLIST ems
		    emid   CDATA  #REQUIRED
		    value  CDATA  #REQUIRED 
		    >
	  
	  ]>		      

<set scale="0.26" name="Fragmentation">
  
  <pdf name="gluon">
    <parameter index="0" name="eta" value="0.003"  error="1.0" state="free" upper="1.0" lower="0.0" />
    <parameter index="1" name="a"   value="6.150" error="1.0" state="free" lower="-2.0" />
    <parameter index="2" name="b"   value="5.379"  error="1.0" state="free"  />
    <parameter index="3" name="c"   value="0.0"     error="0.0" state="fixed" />
  </pdf>
  
  <pdf name="u" pid="P001" >
    <parameter index="0" name="eta" value="0.146"  error="1.0"  state="free" upper="1.0" lower="0.0" />
    <parameter index="1" name="a"   value="0.938" error="10.0" state="free" lower="-2.0"/>
    <parameter index="2" name="b"   value="7.734" error="10.0" state="free" />
    <parameter index="3" name="c"   value="0.0"     error="0.0"  state="fixed" />
  </pdf>

  <pdf name="c" pid="P003" >
    <parameter index="0" name="eta" value="0.084" error="1.0" state="free" upper="1.0" lower="0.0" />
    <parameter index="1" name="a"   value="-0.636" error="1.0" state="free" lower="-2.0" />
    <parameter index="2" name="b"   value="2.486" error="1.0" state="free" />
    <parameter index="3" name="c"   value="0.0"    error="0.0" state="fixed" />
  </pdf>

  <pdf name="b" pid="P004" >
    <parameter index="0" name="eta" value="0.137"  error="1.0" state="free" upper="1.0" lower="0.0" />
    <parameter index="1" name="a"   value="-0.736" error="1.0" state="free" lower="-2.0" />
    <parameter index="2" name="b"   value="3.012"  error="1.0" state="free" />
    <parameter index="3" name="c"   value="0.0"     error="0.0" state="fixed" />
  </pdf>

  <pdf name="d" pid="P001" ></pdf>
  <pdf name="s" src="P001" ></pdf>  
  <pdf name="u-bar" src="P001" ></pdf>
  <pdf name="d-bar" src="P001" ></pdf>
  <pdf name="s-bar" src="P001" ></pdf>
  <pdf name="c-bar" src="P003" ></pdf>
  <pdf name="b-bar" src="P004" ></pdf>

</set>
