<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE set [
<!ELEMENT set (pdf*)>
<!ATTLIST set
  scale CDATA #REQUIRED
  name  CDATA #REQUIRED >
<!ELEMENT pdf (parameter*) >
<!ATTLIST pdf
  name CDATA #REQUIRED
  pid  ID    #IMPLIED
  src  IDREF #IMPLIED
  dfav IDREF #IMPLIED
  fav  IDREF #IMPLIED
>
<!ELEMENT parameter (ems*) >
<!ATTLIST parameter
  index  CDATA #REQUIRED
  name   CDATA #IMPLIED
  value  CDATA #REQUIRED
  error  CDATA #IMPLIED
  state  (fixed|free|add|multi) #REQUIRED
  upper  CDATA #IMPLIED
  lower  CDATA #IMPLIED
  emid   CDATA #IMPLIED
>
<!ELEMENT ems EMPTY >
<!ATTLIST ems
  emid   CDATA  #REQUIRED
  value  CDATA  #REQUIRED
>
]>

<set scale="1" name="Fragmentation">
<pdf name="gluon">
<parameter emid="397127632-0" index="0" name="N" value="0.00571741" error="0.0140387" state="free" upper="1" lower="0">
<ems emid="0" value ="0.000199405"/>
<ems emid="1" value ="-0.000777097"/>
<ems emid="2" value ="0.00103162"/>
<ems emid="3" value ="-0.000691844"/>
<ems emid="4" value ="6.53034e-06"/>
<ems emid="5" value ="-0.000672897"/>
<ems emid="6" value ="-0.00063375"/>
<ems emid="7" value ="-2.46092e-06"/>
<ems emid="8" value ="0.00164613"/>
<ems emid="9" value ="0.0118757"/>
<ems emid="10" value ="-0.000134605"/>
<ems emid="11" value ="0.00194215"/>
<ems emid="12" value ="0.00253456"/>
<ems emid="13" value ="-3.91843e-05"/>
<ems emid="14" value ="9.70511e-05"/>
<ems emid="15" value ="0.000757373"/>
</parameter>
<parameter index="1" name="a" value="11.0534" error="0.172048" state="fixed" upper="100" lower="-2"></parameter>
<parameter index="2" name="b" value="6.65631" error="1.24374" state="fixed" upper="100" lower="-100"></parameter>
</pdf>
<pdf name="s-bar" pid="s-bar">
<parameter emid="397127632-1" index="0" name="N" value="0.392287" error="0.0583063" state="free" upper="1" lower="0">
<ems emid="0" value ="-0.000777097"/>
<ems emid="1" value ="0.00341591"/>
<ems emid="2" value ="-0.00553264"/>
<ems emid="3" value ="0.00139178"/>
<ems emid="4" value ="-2.9833e-05"/>
<ems emid="5" value ="0.00266411"/>
<ems emid="6" value ="0.00252225"/>
<ems emid="7" value ="-1.35979e-05"/>
<ems emid="8" value ="-0.00323002"/>
<ems emid="9" value ="-0.0413843"/>
<ems emid="10" value ="0.000479249"/>
<ems emid="11" value ="-0.00679146"/>
<ems emid="12" value ="-0.00901246"/>
<ems emid="13" value ="0.000147496"/>
<ems emid="14" value ="-0.00476779"/>
<ems emid="15" value ="-0.00598467"/>
</parameter>
<parameter emid="397127632-2" index="1" name="a" value="-0.703209" error="0.154131" state="free" upper="100" lower="-2">
<ems emid="0" value ="0.00103162"/>
<ems emid="1" value ="-0.00553264"/>
<ems emid="2" value ="0.0237577"/>
<ems emid="3" value ="0.0207107"/>
<ems emid="4" value ="5.50615e-05"/>
<ems emid="5" value ="-0.00533961"/>
<ems emid="6" value ="-0.00663466"/>
<ems emid="7" value ="0.000108541"/>
<ems emid="8" value ="-0.0155558"/>
<ems emid="9" value ="0.0375273"/>
<ems emid="10" value ="-0.000689129"/>
<ems emid="11" value ="-0.00252494"/>
<ems emid="12" value ="-0.0102858"/>
<ems emid="13" value ="-0.000190667"/>
<ems emid="14" value ="-0.00535692"/>
<ems emid="15" value ="0.00984739"/>
</parameter>
<parameter emid="397127632-3" index="2" name="b" value="1.47634" error="0.210017" state="free" upper="100" lower="-100">
<ems emid="0" value ="-0.000691844"/>
<ems emid="1" value ="0.00139178"/>
<ems emid="2" value ="0.0207107"/>
<ems emid="3" value ="0.0441072"/>
<ems emid="4" value ="1.99877e-05"/>
<ems emid="5" value ="-0.000965162"/>
<ems emid="6" value ="-0.00533682"/>
<ems emid="7" value ="0.000110106"/>
<ems emid="8" value ="-0.0388895"/>
<ems emid="9" value ="-0.0903469"/>
<ems emid="10" value ="0.000367479"/>
<ems emid="11" value ="-0.02833"/>
<ems emid="12" value ="-0.0636635"/>
<ems emid="13" value ="0.000135437"/>
<ems emid="14" value ="-0.0148524"/>
<ems emid="15" value ="0.00260509"/>
</parameter>
</pdf>
<pdf name="u" pid="u">
<parameter emid="397127632-4" index="0" name="N" value="0.0612888" error="0.00350605" state="free" upper="1" lower="0">
<ems emid="0" value ="6.53034e-06"/>
<ems emid="1" value ="-2.9833e-05"/>
<ems emid="2" value ="5.50615e-05"/>
<ems emid="3" value ="1.99877e-05"/>
<ems emid="4" value ="1.22933e-05"/>
<ems emid="5" value ="-0.000380388"/>
<ems emid="6" value ="-0.000354497"/>
<ems emid="7" value ="-2.25396e-06"/>
<ems emid="8" value ="0.000254363"/>
<ems emid="9" value ="0.000400162"/>
<ems emid="10" value ="-4.64062e-06"/>
<ems emid="11" value ="9.81871e-05"/>
<ems emid="12" value ="0.000159443"/>
<ems emid="13" value ="-1.18045e-06"/>
<ems emid="14" value ="0.000103685"/>
<ems emid="15" value ="0.000112465"/>
</parameter>
<parameter emid="397127632-5" index="1" name="a" value="-0.947582" error="0.117499" state="free" upper="100" lower="-2">
<ems emid="0" value ="-0.000672897"/>
<ems emid="1" value ="0.00266411"/>
<ems emid="2" value ="-0.00533961"/>
<ems emid="3" value ="-0.000965162"/>
<ems emid="4" value ="-0.000380388"/>
<ems emid="5" value ="0.0138066"/>
<ems emid="6" value ="0.013576"/>
<ems emid="7" value ="7.27266e-05"/>
<ems emid="8" value ="-0.0111465"/>
<ems emid="9" value ="-0.0409088"/>
<ems emid="10" value ="0.000501875"/>
<ems emid="11" value ="-0.00635015"/>
<ems emid="12" value ="-0.00829594"/>
<ems emid="13" value ="0.000130706"/>
<ems emid="14" value ="-0.000223458"/>
<ems emid="15" value ="-0.00397953"/>
</parameter>
<parameter emid="397127632-6" index="2" name="b" value="0.959157" error="0.128414" state="free" upper="100" lower="-100">
<ems emid="0" value ="-0.00063375"/>
<ems emid="1" value ="0.00252225"/>
<ems emid="2" value ="-0.00663466"/>
<ems emid="3" value ="-0.00533682"/>
<ems emid="4" value ="-0.000354497"/>
<ems emid="5" value ="0.013576"/>
<ems emid="6" value ="0.0164901"/>
<ems emid="7" value ="6.60782e-05"/>
<ems emid="8" value ="-0.00961079"/>
<ems emid="9" value ="-0.0374452"/>
<ems emid="10" value ="0.00049062"/>
<ems emid="11" value ="-0.0024193"/>
<ems emid="12" value ="0.00321478"/>
<ems emid="13" value ="0.000124341"/>
<ems emid="14" value ="0.000848795"/>
<ems emid="15" value ="-0.00390173"/>
</parameter>
</pdf>
<pdf name="d" pid="d">
<parameter emid="397127632-7" index="0" name="N" value="0.0125176" error="0.00229475" state="free" upper="1" lower="0">
<ems emid="0" value ="-2.46092e-06"/>
<ems emid="1" value ="-1.35979e-05"/>
<ems emid="2" value ="0.000108541"/>
<ems emid="3" value ="0.000110106"/>
<ems emid="4" value ="-2.25396e-06"/>
<ems emid="5" value ="7.27266e-05"/>
<ems emid="6" value ="6.60782e-05"/>
<ems emid="7" value ="5.26663e-06"/>
<ems emid="8" value ="-0.000852307"/>
<ems emid="9" value ="-0.0013367"/>
<ems emid="10" value ="1.86632e-06"/>
<ems emid="11" value ="3.21035e-06"/>
<ems emid="12" value ="-2.69248e-06"/>
<ems emid="13" value ="5.70032e-07"/>
<ems emid="14" value ="7.48583e-05"/>
<ems emid="15" value ="7.55088e-05"/>
</parameter>
<parameter emid="397127632-8" index="1" name="a" value="-0.24875" error="0.442335" state="free" upper="100" lower="-2">
<ems emid="0" value ="0.00164613"/>
<ems emid="1" value ="-0.00323002"/>
<ems emid="2" value ="-0.0155558"/>
<ems emid="3" value ="-0.0388895"/>
<ems emid="4" value ="0.000254363"/>
<ems emid="5" value ="-0.0111465"/>
<ems emid="6" value ="-0.00961079"/>
<ems emid="7" value ="-0.000852307"/>
<ems emid="8" value ="0.195733"/>
<ems emid="9" value ="0.427878"/>
<ems emid="10" value ="-0.000951856"/>
<ems emid="11" value ="0.0209499"/>
<ems emid="12" value ="0.057435"/>
<ems emid="13" value ="-0.000332185"/>
<ems emid="14" value ="-0.00215254"/>
<ems emid="15" value ="-0.0100856"/>
</parameter>
<parameter emid="397127632-9" index="2" name="b" value="5.42548" error="1.20355" state="free" upper="100" lower="-100">
<ems emid="0" value ="0.0118757"/>
<ems emid="1" value ="-0.0413843"/>
<ems emid="2" value ="0.0375273"/>
<ems emid="3" value ="-0.0903469"/>
<ems emid="4" value ="0.000400162"/>
<ems emid="5" value ="-0.0409088"/>
<ems emid="6" value ="-0.0374452"/>
<ems emid="7" value ="-0.0013367"/>
<ems emid="8" value ="0.427878"/>
<ems emid="9" value ="1.4486"/>
<ems emid="10" value ="-0.00804376"/>
<ems emid="11" value ="0.123059"/>
<ems emid="12" value ="0.246711"/>
<ems emid="13" value ="-0.00235778"/>
<ems emid="14" value ="-0.0261242"/>
<ems emid="15" value ="0.000140358"/>
</parameter>
</pdf>
<pdf name="d-bar" src="d"></pdf>
<pdf name="u-bar" src="d"></pdf>
<pdf name="s" src="d"></pdf>
<pdf name="c" pid="CHARM">
<parameter emid="397127632-10" index="0" name="N" value="0.0960954" error="0.0105004" state="free" upper="1" lower="0">
<ems emid="0" value ="-0.000134605"/>
<ems emid="1" value ="0.000479249"/>
<ems emid="2" value ="-0.000689129"/>
<ems emid="3" value ="0.000367479"/>
<ems emid="4" value ="-4.64062e-06"/>
<ems emid="5" value ="0.000501875"/>
<ems emid="6" value ="0.00049062"/>
<ems emid="7" value ="1.86632e-06"/>
<ems emid="8" value ="-0.000951856"/>
<ems emid="9" value ="-0.00804376"/>
<ems emid="10" value ="0.000110306"/>
<ems emid="11" value ="-0.00150047"/>
<ems emid="12" value ="-0.00187694"/>
<ems emid="13" value ="2.64518e-05"/>
<ems emid="14" value ="0.000214533"/>
<ems emid="15" value ="-0.000377952"/>
</parameter>
<parameter emid="397127632-11" index="1" name="a" value="0.312819" error="0.237494" state="free" upper="100" lower="-2">
<ems emid="0" value ="0.00194215"/>
<ems emid="1" value ="-0.00679146"/>
<ems emid="2" value ="-0.00252494"/>
<ems emid="3" value ="-0.02833"/>
<ems emid="4" value ="9.81871e-05"/>
<ems emid="5" value ="-0.00635015"/>
<ems emid="6" value ="-0.0024193"/>
<ems emid="7" value ="3.21035e-06"/>
<ems emid="8" value ="0.0209499"/>
<ems emid="9" value ="0.123059"/>
<ems emid="10" value ="-0.00150047"/>
<ems emid="11" value ="0.0564082"/>
<ems emid="12" value ="0.10919"/>
<ems emid="13" value ="-0.000385008"/>
<ems emid="14" value ="-0.000887661"/>
<ems emid="15" value ="0.00314205"/>
</parameter>
<parameter emid="397127632-12" index="2" name="b" value="4.20648" error="0.517136" state="free" upper="100" lower="-100">
<ems emid="0" value ="0.00253456"/>
<ems emid="1" value ="-0.00901246"/>
<ems emid="2" value ="-0.0102858"/>
<ems emid="3" value ="-0.0636635"/>
<ems emid="4" value ="0.000159443"/>
<ems emid="5" value ="-0.00829594"/>
<ems emid="6" value ="0.00321478"/>
<ems emid="7" value ="-2.69248e-06"/>
<ems emid="8" value ="0.057435"/>
<ems emid="9" value ="0.246711"/>
<ems emid="10" value ="-0.00187694"/>
<ems emid="11" value ="0.10919"/>
<ems emid="12" value ="0.267432"/>
<ems emid="13" value ="-0.000510793"/>
<ems emid="14" value ="0.00340149"/>
<ems emid="15" value ="-0.00299807"/>
</parameter>
</pdf>
<pdf name="b" pid="BOTTOM">
<parameter emid="397127632-13" index="0" name="N" value="0.0621512" error="0.0030367" state="free" upper="1" lower="0">
<ems emid="0" value ="-3.91843e-05"/>
<ems emid="1" value ="0.000147496"/>
<ems emid="2" value ="-0.000190667"/>
<ems emid="3" value ="0.000135437"/>
<ems emid="4" value ="-1.18045e-06"/>
<ems emid="5" value ="0.000130706"/>
<ems emid="6" value ="0.000124341"/>
<ems emid="7" value ="5.70032e-07"/>
<ems emid="8" value ="-0.000332185"/>
<ems emid="9" value ="-0.00235778"/>
<ems emid="10" value ="2.64518e-05"/>
<ems emid="11" value ="-0.000385008"/>
<ems emid="12" value ="-0.000510793"/>
<ems emid="13" value ="9.22201e-06"/>
<ems emid="14" value ="-3.79371e-06"/>
<ems emid="15" value ="-0.000151224"/>
</parameter>
<parameter index="1" name="a" value="-0.163766" error="0.00172089" state="fixed" upper="100" lower="-2"></parameter>
<parameter index="2" name="b" value="8.35263" error="0.00828076" state="fixed" upper="100" lower="-100"></parameter>
</pdf>
<pdf name="c-bar" src="CHARM"></pdf>
<pdf name="b-bar" src="BOTTOM"></pdf>
</set>
<!--    Fitting status [Sun Feb  8 22:48:05 2009]
   original configuration file  [/home/imazu/work/QCD/fit_work/FFKA_fit/set2/Multi_FFK_NLO_0.05-0.8_werr_BB.xml]

 ===========================================================
   Arguments of the operation
     command: testMultiFragFit
           FF=/home/imazu/work/QCD/fit_work/FFKA_fit/set2/Multi_FF_NLO_0.05-0.8_werr.xml
           FFK=/home/imazu/work/QCD/fit_work/FFKA_fit/set2/Multi_FFK_NLO_0.05-0.8_werr_BB.xml
           MRST=MRST2001.xml
           MRSTMz=0.1190
           NoCondition=__NO_VALUE__
           UPDFangle=0.60
           UPDFoffset=4.5
           errorMatrix=__NO_VALUE__
           expdata=/home/imazu/work/QCD/fit_work/FFKA_fit/set2/ka.xml
           fit=kaon,norm
           zmax=0.8
           zmin=0.05
 ===========================================================
   elapsed time                 0:13:31
   number of iteration              522
   total chi2                   156.506
   number of data point             181
   number of free param              16
   d.o.f                            164
   reduced chi2                0.954302

*******************  Fitting condition *********************
  z range:  0.05 -   0.8
      PIp :      0.05 -   0.8
      KAp :      0.05 -   0.8
      PRp :      0.05 -   0.8
      REp :      0.05 -   0.8
      HAp :      0.05 -   0.8
      PIm :      0.05 -   0.8
      KAm :      0.05 -   0.8
      PRm :      0.05 -   0.8
      REm :      0.05 -   0.8
      HAm :      0.05 -   0.8
       P0 :      0.05 -   0.8
*************** Mellin Inversion condition *****************
********************  Data listing  ***********************
      zmin      zmax      zave Q2( ave )            xmin            xmax            xave       sigma      dsigma         fit id dsetid        chi2             DataSetInfo
    0.0571    0.0914         0      1156               0               0               0        10.5         2.3      7.9753  0      1     1.20494      TASSO_34_1989_KApm
    0.0914     0.114         0      1156               0               0               0         6.3         2.8     5.94715  0      1   0.0158807      TASSO_34_1989_KApm
     0.171     0.217         0      1156               0               0               0        3.57        0.61     2.86001  0      1     1.35472      TASSO_34_1989_KApm
     0.217     0.343         0      1156               0               0               0        1.75        0.28     1.58224  0      1    0.358992      TASSO_34_1989_KApm
      0.05     0.055         0       841               0               0               0        8.73        0.65     10.1312  0      1     4.64703        TPC_29_1988_KApm
     0.055      0.06         0       841               0               0               0        8.48        0.74     9.49456  0      1     1.87971        TPC_29_1988_KApm
      0.06     0.065         0       841               0               0               0         9.2         1.3     8.93276  0      1   0.0422573        TPC_29_1988_KApm
     0.065      0.07         0       841               0               0               0         8.8         2.3     8.43109  0      1    0.025727        TPC_29_1988_KApm
      0.09       0.1         0       841               0               0               0         5.6         1.5     6.36163  0      1    0.257815        TPC_29_1988_KApm
       0.1      0.11         0       841               0               0               0        6.32        0.92     5.80084  0      1    0.318444        TPC_29_1988_KApm
      0.11      0.12         0       841               0               0               0        5.13        0.61     5.31188  0      1   0.0888975        TPC_29_1988_KApm
      0.12      0.13         0       841               0               0               0        5.13        0.49      4.8816  0      1    0.256977        TPC_29_1988_KApm
      0.13      0.14         0       841               0               0               0           5        0.38     4.49941  0      1     1.73542        TPC_29_1988_KApm
      0.25       0.3         0       841               0               0               0        1.73        0.11     1.62322  0      1    0.942341        TPC_29_1988_KApm
       0.3      0.35         0       841               0               0               0       1.161       0.073     1.14175  0      1   0.0695378        TPC_29_1988_KApm
      0.35       0.4         0       841               0               0               0       0.842       0.055    0.799331  0      1    0.601866        TPC_29_1988_KApm
       0.4       0.5         0       841               0               0               0        0.47        0.03    0.466181  0      1   0.0162031        TPC_29_1988_KApm
       0.5       0.6         0       841               0               0               0       0.249        0.02    0.210988  0      1     3.61223        TPC_29_1988_KApm
       0.6       0.7         0       841               0               0               0        0.09       0.012    0.088129  0      1   0.0243092        TPC_29_1988_KApm
     0.055      0.06         0   8317.44               0               0               0       11.96       2.178     12.8526  0      1    0.164693SLD__inclusive_91.2_1999_KApm
      0.06     0.066         0   8317.44               0               0               0       11.03     1.36125     11.7856  0      1    0.301675SLD__inclusive_91.2_1999_KApm
     0.066     0.071         0   8317.44               0               0               0       11.37    0.984124     10.8618  0      1     0.27444SLD__inclusive_91.2_1999_KApm
     0.071     0.077         0   8317.44               0               0               0        9.38    0.904268     10.0576  0      1    0.550233SLD__inclusive_91.2_1999_KApm
     0.077     0.082         0   8317.44               0               0               0        9.51     0.87818     9.34292  0      1   0.0389862SLD__inclusive_91.2_1999_KApm
     0.082     0.088         0   8317.44               0               0               0        8.68    0.843801     8.70574  0      1 0.000553428SLD__inclusive_91.2_1999_KApm
     0.088     0.099         0   8317.44               0               0               0        7.96    0.747329     7.84489  0      1   0.0259614SLD__inclusive_91.2_1999_KApm
     0.099      0.11         0   8317.44               0               0               0        7.37    0.715891      6.8946  0      1    0.449672SLD__inclusive_91.2_1999_KApm
      0.11     0.121         0   8317.44               0               0               0        6.74    0.704911     6.09849  0      1    0.838891SLD__inclusive_91.2_1999_KApm
     0.121     0.143         0   8317.44               0               0               0        5.24    0.675426     5.13695  0      1   0.0248732SLD__inclusive_91.2_1999_KApm
     0.143     0.164         0   8317.44               0               0               0        4.08    0.894427     4.15568  0      1  0.00663783SLD__inclusive_91.2_1999_KApm
     0.208      0.23         0   8317.44               0               0               0        2.34    0.310483      2.3173  0      1     0.00611SLD__inclusive_91.2_1999_KApm
      0.23     0.252         0   8317.44               0               0               0       1.947   0.0864523     1.92704  0      1   0.0605062SLD__inclusive_91.2_1999_KApm
     0.252     0.274         0   8317.44               0               0               0       1.603   0.0708025     1.60939  0      1  0.00560543SLD__inclusive_91.2_1999_KApm
     0.274     0.296         0   8317.44               0               0               0       1.281   0.0604649     1.34936  0      1     1.24419SLD__inclusive_91.2_1999_KApm
     0.296     0.318         0   8317.44               0               0               0       1.127   0.0540833     1.13531  0      1   0.0194491SLD__inclusive_91.2_1999_KApm
     0.318     0.351         0   8317.44               0               0               0       0.933   0.0434166    0.920118  0      1    0.096753SLD__inclusive_91.2_1999_KApm
     0.351     0.384         0   8317.44               0               0               0       0.669   0.0370135     0.71682  0      1      1.6355SLD__inclusive_91.2_1999_KApm
     0.384     0.417         0   8317.44               0               0               0       0.541   0.0347131        0.56  0      1    0.287748SLD__inclusive_91.2_1999_KApm
     0.417      0.45         0   8317.44               0               0               0       0.493   0.0347131    0.437711  0      1     2.56404SLD__inclusive_91.2_1999_KApm
      0.45     0.482         0   8317.44               0               0               0       0.357   0.0304795    0.342832  0      1    0.223217SLD__inclusive_91.2_1999_KApm
     0.482     0.526         0   8317.44               0               0               0       0.273   0.0261725    0.257118  0      1     0.37633SLD__inclusive_91.2_1999_KApm
     0.526      0.57         0   8317.44               0               0               0        0.18   0.0212603    0.182237  0      1  0.00988425SLD__inclusive_91.2_1999_KApm
      0.57     0.658         0   8317.44               0               0               0       0.122   0.0155563    0.107713  0      1    0.852037SLD__inclusive_91.2_1999_KApm
     0.658     0.768         0   8317.44               0               0               0       0.048   0.0108167   0.0450022  0      1   0.0783794SLD__inclusive_91.2_1999_KApm
     0.055     0.066         0   8317.44               0               0               0        10.7         3.6     10.2634  1      1   0.0147083    SLD_c_91.2_1999_KApm
     0.066     0.077         0   8317.44               0               0               0         9.5         3.1     9.31958  1      1  0.00338716    SLD_c_91.2_1999_KApm
     0.077     0.088         0   8317.44               0               0               0         8.9           3     8.49856  1      1   0.0179056    SLD_c_91.2_1999_KApm
     0.088     0.099         0   8317.44               0               0               0        10.5           3     7.78784  1      1    0.817311    SLD_c_91.2_1999_KApm
     0.099      0.11         0   8317.44               0               0               0        10.2         3.2     7.17375  1      1    0.894354    SLD_c_91.2_1999_KApm
      0.11     0.132         0   8317.44               0               0               0         8.1         2.5     6.39341  1      1    0.465994    SLD_c_91.2_1999_KApm
     0.132     0.164         0   8317.44               0               0               0           8         2.6     5.32639  1      1     1.05743    SLD_c_91.2_1999_KApm
     0.208      0.23         0   8317.44               0               0               0        2.64         0.7      3.2666  1      1    0.801275    SLD_c_91.2_1999_KApm
      0.23     0.274         0   8317.44               0               0               0        3.29        0.37     2.60191  1      1     3.45846    SLD_c_91.2_1999_KApm
     0.274     0.318         0   8317.44               0               0               0         1.3        0.27     1.89846  1      1     4.91288    SLD_c_91.2_1999_KApm
     0.318     0.384         0   8317.44               0               0               0        0.66        0.17     1.25607  1      1     12.2942    SLD_c_91.2_1999_KApm
     0.384     0.471         0   8317.44               0               0               0        0.65        0.12    0.667052  1      1    0.020193    SLD_c_91.2_1999_KApm
     0.471     0.603         0   8317.44               0               0               0       0.229       0.073    0.239805  1      1   0.0219086    SLD_c_91.2_1999_KApm
     0.603     0.768         0   8317.44               0               0               0      -0.003       0.046   0.0426001  1      1    0.982689    SLD_c_91.2_1999_KApm
     0.055     0.066         0   8317.44               0               0               0        15.2         1.4     17.1041  2      1     1.84977   SLD__b_91.2_1999_KApm
     0.066     0.077         0   8317.44               0               0               0        14.5         1.2     14.4944  2      1 2.18505e-05   SLD__b_91.2_1999_KApm
     0.077     0.088         0   8317.44               0               0               0        13.4         1.2     12.3886  2      1     0.71032   SLD__b_91.2_1999_KApm
     0.088     0.099         0   8317.44               0               0               0        10.6         1.1     10.6502  2      1  0.00208023   SLD__b_91.2_1999_KApm
     0.099      0.11         0   8317.44               0               0               0         8.4         1.2     9.19108  2      1    0.434588   SLD__b_91.2_1999_KApm
      0.11     0.132         0   8317.44               0               0               0        8.71        0.98     7.42424  2      1     1.72136   SLD__b_91.2_1999_KApm
     0.132     0.164         0   8317.44               0               0               0        3.65        0.94     5.27021  2      1      2.9709   SLD__b_91.2_1999_KApm
     0.208      0.23         0   8317.44               0               0               0        2.01        0.27     2.13582  2      1     0.21715   SLD__b_91.2_1999_KApm
      0.23     0.274         0   8317.44               0               0               0        1.18        0.14     1.40855  2      1     2.66495   SLD__b_91.2_1999_KApm
     0.274     0.318         0   8317.44               0               0               0       0.811       0.098    0.785315  2      1     0.06869   SLD__b_91.2_1999_KApm
     0.318     0.384         0   8317.44               0               0               0       0.496        0.06    0.372727  2      1     4.22117   SLD__b_91.2_1999_KApm
     0.384     0.471         0   8317.44               0               0               0       0.113       0.035    0.122963  2      1    0.081028   SLD__b_91.2_1999_KApm
     0.471     0.603         0   8317.44               0               0               0       0.043       0.021   0.0216736  2      1     1.03133   SLD__b_91.2_1999_KApm
     0.603     0.768         0   8317.44               0               0               0        0.02       0.014 0.000882719  2      1     1.86465   SLD__b_91.2_1999_KApm
 0.0888158  0.108553         0   8317.44               0               0               0      8.2536    0.707902     7.39149  0      1     1.48312     OPAL_91.2_1994_KApm
  0.108553  0.132675         0   8317.44               0               0               0      6.2928      0.4326     5.78911  0      1     1.35566     OPAL_91.2_1994_KApm
  0.132675  0.161842         0   8317.44               0               0               0      4.6968    0.277374     4.42189  0      1    0.982319     OPAL_91.2_1994_KApm
  0.161842  0.197807         0   8317.44               0               0               0     3.49752    0.196874     3.27061  0      1     1.32843     OPAL_91.2_1994_KApm
  0.197807  0.241447         0   8317.44               0               0               0     2.44416    0.135041      2.3162  0      1    0.897937     OPAL_91.2_1994_KApm
  0.241447  0.294956         0   8317.44               0               0               0     1.59144   0.0851878     1.55435  0      1    0.189577     OPAL_91.2_1994_KApm
  0.294956  0.360307         0   8317.44               0               0               0      1.0032   0.0564041    0.977971  0      1    0.200071     OPAL_91.2_1994_KApm
  0.360307  0.439912         0   8317.44               0               0               0     0.57912   0.0347279    0.568563  0      1   0.0924067     OPAL_91.2_1994_KApm
  0.439912   0.65636         0   8317.44               0               0               0     0.19152     0.01442    0.201922  0      1     0.52035     OPAL_91.2_1994_KApm
      0.07     0.075         0   8317.44               0               0               0        10.6     1.31469     10.2658  0      1  0.00862059   ALEPH__91.2_1995_KApm
     0.075      0.08         0   8317.44               0               0               0        9.53      1.0139     9.59281  0      1   0.0662801   ALEPH__91.2_1995_KApm
      0.08     0.085         0   8317.44               0               0               0        9.15    0.861278     8.98643  0      1 0.000659623   ALEPH__91.2_1995_KApm
     0.085      0.09         0   8317.44               0               0               0        8.41    0.740405     8.43605  0      1   0.0732375   ALEPH__91.2_1995_KApm
      0.09       0.1         0   8317.44               0               0               0        7.96    0.577235     7.70339  0      1   0.0284909   ALEPH__91.2_1995_KApm
       0.1      0.11         0   8317.44               0               0               0        7.26    0.487647     6.85426  0      1    0.293333   ALEPH__91.2_1995_KApm
      0.11      0.12         0   8317.44               0               0               0        6.34    0.386005     6.13093  0      1   0.0455549   ALEPH__91.2_1995_KApm
      0.12      0.13         0   8317.44               0               0               0        5.63    0.338378     5.50963  0      1 0.000371878   ALEPH__91.2_1995_KApm
      0.13      0.14         0   8317.44               0               0               0        4.94    0.297321     4.97181  0      1    0.204788   ALEPH__91.2_1995_KApm
      0.14      0.15         0   8317.44               0               0               0        4.39     0.25632     4.50262  0      1    0.643802   ALEPH__91.2_1995_KApm
      0.15      0.16         0   8317.44               0               0               0        4.22    0.237697     4.09015  0      1   0.0363718   ALEPH__91.2_1995_KApm
      0.16      0.18         0   8317.44               0               0               0        3.63    0.189737     3.56221  0      1 0.000940054   ALEPH__91.2_1995_KApm
      0.18       0.2         0   8317.44               0               0               0         3.1    0.158114     2.97678  0      1    0.152329   ALEPH__91.2_1995_KApm
       0.2      0.25         0   8317.44               0               0               0       2.245    0.112792      2.2176  0      1   0.0266738   ALEPH__91.2_1995_KApm