<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE set [
<!ELEMENT set (pdf*)>
<!ATTLIST set
  scale CDATA #REQUIRED
  name  CDATA #REQUIRED >
<!ELEMENT pdf (parameter*) >
<!ATTLIST pdf
  name CDATA #REQUIRED
  pid  ID    #IMPLIED
  src  IDREF #IMPLIED
  dfav IDREF #IMPLIED
  fav  IDREF #IMPLIED
>
<!ELEMENT parameter (ems*) >
<!ATTLIST parameter
  index  CDATA #REQUIRED
  name   CDATA #IMPLIED
  value  CDATA #REQUIRED
  error  CDATA #IMPLIED
  state  (fixed|free) #REQUIRED
  upper  CDATA #IMPLIED
  lower  CDATA #IMPLIED
  emid   CDATA #IMPLIED
>
<!ELEMENT ems EMPTY >
<!ATTLIST ems
  emid   CDATA  #REQUIRED
  value  CDATA  #REQUIRED
>
]>

<set scale="1" name="polDIS SU(3)">
<pdf name="gluon" pid="GLUON">
<parameter index="0" name="eta" value="0.477822" error="0.199719" state="free" upper="100" lower="-100"></parameter>
<parameter index="1" name="a" value="4.12193" error="1.17733" state="free" upper="100" lower="-1"></parameter>
<parameter index="2" name="b" value="4" error="0" state="free" upper="100" lower="-1"></parameter>
<parameter index="3" name="c" value="0" error="0" state="free" upper="100" lower="-40"></parameter>
</pdf>
<pdf name="a0" pid="a0">
<parameter index="0" name="eta" value="0.183038" error="0.0215625" state="free" upper="100" lower="-100"></parameter>
<parameter index="1" name="a" value="1.11529" error="0.11364" state="free" upper="100" lower="-2"></parameter>
<parameter index="2" name="b" value="4.60911" error="0.288191" state="free" upper="100" lower="-1"></parameter>
<parameter index="3" name="c" value="7.93182" error="0.50265" state="free" upper="100" lower="-100"></parameter>
</pdf>
<pdf name="a3" pid="a3">
<parameter index="0" name="eta" value="1.269" error="0" state="free" upper="100" lower="-100"></parameter>
<parameter index="1" name="a" value="0.686158" error="0.0288063" state="free" upper="100" lower="-2"></parameter>
<parameter index="2" name="b" value="1.57933" error="0.0979284" state="free" upper="100" lower="-1"></parameter>
<parameter index="3" name="c" value="0" error="0" state="fixed" upper="100" lower="-100"></parameter>
</pdf>
<pdf name="a8" src="a3">
<parameter index="0" name="eta" value="0.586" error="0" state="free" upper="100" lower="-100"></parameter>
<parameter index="1" name="a" value="2.35138" error="0.418495" state="free" upper="100" lower="-2"></parameter>
<parameter index="2" name="b" value="22.0654" error="4.04284" state="free" upper="100" lower="-1"></parameter>
</pdf>
</set>
<!--    Fitting status [Wed Oct  1 18:32:37 2008]
   original configuration file  [polPDF_NLO_0.xml]

   elapsed time                 0: 1:33
   number of iteration              175
   total chi2                   429.988
   number of data point             363
   number of free param              10
   d.o.f                            352
   reduced chi2                 1.22156

Mellin Inversion Integration Path:
   starting point                     2
   angle                           0.55
   length                            15


************************ Fitting condition  ************************
  x minimum               0.001
  x maximum                 0.9
  Q^2 minimum                 1

*************************** Data Listing ***************************
         x       Q^2          g1        stat         fit       chi^2                    info
     0.015       3.5       0.279       0.361    0.505505    0.393677            EMC,1989,g1p
     0.025       4.5       0.564        0.26    0.444541    0.211103            EMC,1989,g1p
     0.035         6       0.115        0.23    0.421255     1.77301            EMC,1989,g1p
      0.05         8       0.254       0.146    0.398315    0.977052            EMC,1989,g1p
     0.078      10.3        0.28       0.093    0.357962    0.702754            EMC,1989,g1p
     0.124      12.9       0.225       0.076    0.302657     1.04408            EMC,1989,g1p
     0.175      15.2       0.311       0.071    0.255767    0.605183            EMC,1989,g1p
     0.248        18       0.253       0.048    0.206732     0.92914            EMC,1989,g1p
     0.344      22.5       0.167       0.044    0.146665    0.213585            EMC,1989,g1p
     0.466      29.5       0.094       0.025   0.0783823     0.39026            EMC,1989,g1p
     0.024      0.51    0.336448   0.0987401           0           0           E143,1998,g1p
     0.027      0.55    0.291438   0.0881091           0           0           E143,1998,g1p
     0.027      1.17   -0.134759    0.286363    0.342828     2.78145           E143,1998,g1p
     0.031      0.59    0.258162   0.0799071           0           0           E143,1998,g1p
     0.031      1.27     0.24195    0.128536    0.334821    0.522051           E143,1998,g1p
     0.035      0.31    0.213035   0.0821072           0           0           E143,1998,g1p
     0.035      0.64    0.166927   0.0679025           0           0           E143,1998,g1p
     0.035       1.4    0.425045   0.0863912    0.332129     1.15676           E143,1998,g1p
     0.039      0.33   0.0504387   0.0777596           0           0           E143,1998,g1p
     0.039      0.68    0.188303   0.0627676           0           0           E143,1998,g1p
     0.039      1.52    0.263994   0.0731551    0.330702    0.831497           E143,1998,g1p
     0.044      0.35    0.207505    0.072431           0           0           E143,1998,g1p
     0.044      0.73    0.229824   0.0550621           0           0           E143,1998,g1p
     0.044      0.98    0.248502     1.33218           0           0           E143,1998,g1p
     0.044      1.65     0.31777   0.0606653    0.328297   0.0301125           E143,1998,g1p
     0.049      0.36    0.195977   0.0707695           0           0           E143,1998,g1p
     0.049      0.78     0.32502   0.0530644           0           0           E143,1998,g1p
     0.049      1.06     0.18445    0.257757    0.289811    0.167087           E143,1998,g1p
     0.049      1.78    0.331225   0.0529959    0.326309  0.00860545           E143,1998,g1p
     0.056      0.38     0.17919    0.068026           0           0           E143,1998,g1p
     0.056      0.57   -0.394176     3.48312           0           0           E143,1998,g1p
     0.056      0.83     0.21913   0.0498024           0           0           E143,1998,g1p
     0.056      1.16    0.281736    0.134465    0.289652  0.00346568           E143,1998,g1p
     0.056      1.92    0.307893   0.0473681    0.321296   0.0800684           E143,1998,g1p
     0.063       0.4     0.11942   0.0658343           0           0           E143,1998,g1p
     0.063       0.6  -0.0404404    0.298248           0           0           E143,1998,g1p
     0.063      0.87    0.284637   0.0489504           0           0           E143,1998,g1p
     0.063      1.26    0.101333   0.0896411    0.288792     4.37321           E143,1998,g1p
     0.063      2.07    0.296313   0.0429438    0.317223     0.23708           E143,1998,g1p
     0.063      2.69     2.57089     1.88186    0.329345      1.4188           E143,1998,g1p
     0.071      0.41    0.134164   0.0684794           0           0           E143,1998,g1p
     0.071      0.64   0.0986765     0.11872           0           0           E143,1998,g1p
     0.071      0.92    0.176491   0.0478341           0           0           E143,1998,g1p
     0.071      1.36    0.255229   0.0726692    0.287131    0.192728           E143,1998,g1p
     0.071      2.22    0.290994   0.0387992     0.31178    0.286997           E143,1998,g1p
     0.071      2.91    0.660065    0.246506    0.323158     1.86795           E143,1998,g1p
     0.079      0.43    0.146462   0.0686948           0           0           E143,1998,g1p
     0.079      0.69     0.23413   0.0756639           0           0           E143,1998,g1p
     0.079      0.97     0.18496   0.0469981           0           0           E143,1998,g1p
     0.079      1.47    0.220053   0.0635709    0.284543     1.02911           E143,1998,g1p
     0.079      2.38    0.333324    0.037233    0.306314    0.526254           E143,1998,g1p
     0.079      3.17    0.388831    0.106045    0.316974    0.459153           E143,1998,g1p
      0.09      0.44   0.0807428   0.0643602           0           0           E143,1998,g1p
      0.09      0.74     0.18749   0.0556004           0           0           E143,1998,g1p
      0.09      1.01    0.242335   0.0462886     0.25788     0.11278           E143,1998,g1p
      0.09      1.58     0.28701   0.0541804    0.279049   0.0215906           E143,1998,g1p
      0.09      2.53     0.25133   0.0363559    0.296979      1.5766           E143,1998,g1p
      0.09      3.48    0.260501   0.0663697    0.307725    0.506265           E143,1998,g1p
     0.101      0.45    0.109015   0.0609201           0           0           E143,1998,g1p
     0.101      0.78    0.163078   0.0472691           0           0           E143,1998,g1p
     0.101      1.06    0.273998    0.045873    0.249654    0.281613           E143,1998,g1p
     0.101      1.69    0.244973    0.049261    0.269424    0.246366           E143,1998,g1p
     0.101      2.69    0.338539   0.0357109    0.286005     2.16407           E143,1998,g1p
     0.101      3.79    0.293457   0.0494085    0.296708  0.00433062           E143,1998,g1p
     0.113      0.47    0.181698    0.057947           0           0           E143,1998,g1p
     0.113      0.82    0.206518   0.0432499           0           0           E143,1998,g1p
     0.113       1.1      0.1897   0.0462959    0.243358     1.34333           E143,1998,g1p
     0.113       1.8    0.252008   0.0448283    0.262714   0.0570338           E143,1998,g1p
     0.113      2.84    0.308696   0.0361653    0.276888    0.773554           E143,1998,g1p
     0.113      4.11    0.304048    0.041891      0.2874    0.157946           E143,1998,g1p
     0.128      0.48  0.00975333   0.0567466           0           0           E143,1998,g1p
     0.128      0.86    0.131861   0.0400466           0           0           E143,1998,g1p
     0.128      1.14    0.224436   0.0456995    0.235462   0.0582108           E143,1998,g1p
     0.128      1.91     0.25443   0.0402304    0.253277 0.000821384           E143,1998,g1p
     0.128         3    0.264904   0.0345527    0.265729 0.000570212           E143,1998,g1p
     0.128      4.44     0.28451    0.036014    0.275526   0.0622253           E143,1998,g1p
     0.144       0.9    0.124777   0.0371676           0           0           E143,1998,g1p
     0.144      1.18     0.20348   0.0449122    0.226095    0.253558           E143,1998,g1p
     0.144      2.03    0.253664   0.0372171     0.24296   0.0827221           E143,1998,g1p
     0.144      3.15    0.219414   0.0339937    0.253851     1.02623           E143,1998,g1p
     0.144      4.78    0.258756   0.0320771    0.263018   0.0176555           E143,1998,g1p
     0.162      0.93    0.169008   0.0342799           0           0           E143,1998,g1p
     0.162      1.22    0.241445   0.0444984    0.215798     0.33218           E143,1998,g1p
     0.162      2.14    0.208008   0.0351069    0.231485    0.447213           E143,1998,g1p
     0.162       3.3    0.280676   0.0330207    0.241185     1.43027           E143,1998,g1p
     0.162      5.13    0.257613   0.0284132    0.249941   0.0729115           E143,1998,g1p
     0.182      0.97    0.216886   0.0322108           0           0           E143,1998,g1p
     0.182      1.25    0.176154   0.0442226    0.204792    0.419356           E143,1998,g1p
     0.182      2.25    0.201196   0.0336631    0.220279    0.321365           E143,1998,g1p
     0.182      3.45     0.25447   0.0325201    0.229101    0.608553           E143,1998,g1p
     0.182      5.49    0.266937   0.0258595    0.237103     1.33098           E143,1998,g1p
     0.205         1    0.160618   0.0304729    0.187352    0.769671           E143,1998,g1p
     0.205      1.29    0.198488   0.0430927    0.194808  0.00729348           E143,1998,g1p
     0.205      2.36    0.207896   0.0317715    0.209698  0.00321634           E143,1998,g1p
     0.205      3.59    0.215903   0.0313523    0.217276  0.00191684           E143,1998,g1p
     0.205      5.86    0.269189   0.0232185    0.224329     3.73291           E143,1998,g1p
      0.23      1.03    0.185677   0.0279634    0.179601   0.0472108           E143,1998,g1p
      0.23      1.32    0.146459   0.0419274    0.186787    0.925161           E143,1998,g1p
      0.23      2.47    0.227678   0.0302763    0.200266    0.819728           E143,1998,g1p
      0.23      3.73    0.241455   0.0304146    0.206451     1.32453           E143,1998,g1p
      0.23      6.23    0.170998   0.0219228    0.211918     3.48399           E143,1998,g1p
     0.259      1.35    0.117115   0.0406925    0.179583     2.35659           E143,1998,g1p
     0.259      2.57    0.252692   0.0286558    0.190722     4.67662           E143,1998,g1p
     0.259      3.85    0.203739   0.0291814    0.194872   0.0923299           E143,1998,g1p
     0.259       6.6    0.252532   0.0201179    0.198172     7.30129           E143,1998,g1p
     0.292      1.37    0.142958   0.0382623    0.172193    0.583811           E143,1998,g1p
     0.292      2.67    0.218842   0.0268059     0.17975     2.12672           E143,1998,g1p
     0.292      3.98    0.160419   0.0279956    0.181514    0.567793           E143,1998,g1p
     0.292      6.97    0.172585   0.0187877    0.182039    0.253201           E143,1998,g1p
     0.329      2.76    0.151916   0.0246546    0.165817    0.317889           E143,1998,g1p
     0.329      4.09    0.165841   0.0272765    0.165177 0.000593305           E143,1998,g1p
     0.329      7.33    0.146568   0.0168308    0.162792    0.929165           E143,1998,g1p
      0.37      2.85    0.161602   0.0225015    0.148133    0.358309           E143,1998,g1p
      0.37       4.2    0.104992    0.025813    0.145484     2.46068           E143,1998,g1p
      0.37      7.69    0.117781   0.0149953    0.140468     2.28901           E143,1998,g1p
     0.416      2.93    0.121028   0.0199044    0.126715   0.0816366           E143,1998,g1p
     0.416       4.3    0.151088   0.0241384    0.122459     1.40668           E143,1998,g1p
     0.416      8.03    0.122672   0.0133562    0.115702    0.272357           E143,1998,g1p
     0.468      3.01    0.102238   0.0175018    0.102333 2.94409e-05           E143,1998,g1p
     0.468       4.4    0.117636   0.0224382    0.097414    0.812216           E143,1998,g1p
     0.468      8.37   0.0875409   0.0116921   0.0898171   0.0378996           E143,1998,g1p
     0.526      4.47   0.0851489   0.0196856   0.0725648    0.408647           E143,1998,g1p
     0.526      8.67   0.0673494  0.00991647   0.0651565   0.0489012           E143,1998,g1p
     0.592      4.55   0.0294715   0.0167417   0.0496733     1.45607           E143,1998,g1p
     0.592      8.98   0.0433585  0.00795984   0.0432871 8.04404e-05           E143,1998,g1p
     0.666      9.26   0.0170601  0.00588894    0.025844     2.22485           E143,1998,g1p
     0.749      9.52   0.0118802  0.00378441   0.0133375     0.14829           E143,1998,g1p
     0.005       1.3        0.75        0.36     0.67638   0.0418207            SMC,1998,g1p
     0.008       2.1        0.48        0.26    0.601582    0.218672            SMC,1998,g1p
     0.014       3.6        0.43        0.15    0.520062    0.360497            SMC,1998,g1p
     0.025       5.7        0.43        0.13    0.458486   0.0480162            SMC,1998,g1p
     0.035       7.8        0.36        0.11    0.434619    0.460162            SMC,1998,g1p
     0.049      10.4        0.38        0.07    0.411487    0.202335            SMC,1998,g1p
     0.077      14.9        0.41        0.04    0.370669    0.966824            SMC,1998,g1p
     0.122      21.3        0.35        0.03    0.314122     1.43028            SMC,1998,g1p
     0.173      27.8        0.28        0.03     0.26322    0.312846            SMC,1998,g1p
     0.242      35.6        0.21        0.02     0.21081  0.00164207            SMC,1998,g1p
     0.342      45.9        0.17        0.02    0.142449     1.89764            SMC,1998,g1p
      0.48        58        0.07        0.01   0.0670102   0.0893883            SMC,1998,g1p
     0.015      1.22    0.360375   0.0675703    0.428383       1.013           E155,2000,g1p
     0.025      1.59    0.282429   0.0396391    0.376619     5.64627           E155,2000,g1p
     0.035      2.05    0.266592   0.0304676    0.359723     9.34349           E155,2000,g1p
      0.05      2.58    0.312704   0.0253544    0.345509     1.67409           E155,2000,g1p
      0.05      4.01    0.683401    0.270898    0.367305     1.36152           E155,2000,g1p
      0.08      3.24    0.285806   0.0165952     0.31655     3.43203           E155,2000,g1p
      0.08      5.36    0.296543   0.0217465    0.334309     3.01598           E155,2000,g1p
     0.125      4.03    0.226623   0.0146208    0.275785     11.3061           E155,2000,g1p
     0.125      7.17    0.265536  0.00889355    0.289436     7.22204           E155,2000,g1p
     0.125     10.99    0.384863   0.0639349    0.298427     1.82775           E155,2000,g1p
     0.175      4.62    0.236221   0.0199014    0.238863   0.0176278           E155,2000,g1p
     0.175       8.9    0.214948   0.0104428    0.249218     10.7695           E155,2000,g1p
     0.175     13.19    0.266309   0.0192092    0.254175    0.399047           E155,2000,g1p
      0.25      5.06    0.200408   0.0128754    0.200795 0.000904937           E155,2000,g1p
      0.25     10.64    0.188551  0.00587553    0.204515      7.3825           E155,2000,g1p
      0.25     17.21    0.221526  0.00783171    0.205447      4.2152           E155,2000,g1p
      0.35      5.51    0.135557   0.0156658    0.153514     1.31387           E155,2000,g1p
      0.35      12.6    0.143721  0.00616827    0.147582    0.391716           E155,2000,g1p
       0.5      5.77   0.0721478  0.00745913   0.0800419     1.12003           E155,2000,g1p
       0.5     14.02   0.0663216  0.00283729   0.0705579      2.2293           E155,2000,g1p
       0.5     26.86   0.0553093  0.00458183   0.0648682      4.3525           E155,2000,g1p
      0.75      15.7  0.00784297  0.00114744   0.0115691      10.545           E155,2000,g1p
      0.75     34.72  0.00527103   0.0038189  0.00957392     1.26953           E155,2000,g1p
    0.0058      0.26      0.2584      0.3138           0           0         HERMES,2006,g1p
    0.0096      0.41      0.1357      0.1632           0           0         HERMES,2006,g1p
    0.0142      0.57      0.2361      0.1229           0           0         HERMES,2006,g1p
     0.019      0.73      0.2416        0.12           0           0         HERMES,2006,g1p
    0.0248      0.82      0.2812       0.089           0           0         HERMES,2006,g1p
    0.0264      1.12      0.4736       0.149    0.341289    0.788537         HERMES,2006,g1p
    0.0325      0.87      0.3781      0.1609           0           0         HERMES,2006,g1p
    0.0329      1.25      0.3459      0.0949    0.327469   0.0377194         HERMES,2006,g1p
    0.0399       0.9      0.3591      0.2147           0           0         HERMES,2006,g1p
    0.0403      1.38      0.2696      0.0706     0.32109    0.531901         HERMES,2006,g1p
    0.0498      0.93      0.2059      0.2534           0           0         HERMES,2006,g1p
    0.0506      1.54       0.264      0.0498    0.314613      1.0329         HERMES,2006,g1p
    0.0643      1.25      0.2637      0.1011    0.287076   0.0534608         HERMES,2006,g1p
    0.0645      1.85      0.2063      0.0591     0.30948     3.04802         HERMES,2006,g1p
    0.0655      2.58      0.1949      0.0702    0.324514     3.40902         HERMES,2006,g1p
    0.0823      1.31      0.2177      0.1049    0.276467    0.313845         HERMES,2006,g1p
    0.0824      2.06      0.3104       0.052       0.297   0.0664006         HERMES,2006,g1p
    0.0835      3.08      0.3535      0.0504     0.31074    0.719806         HERMES,2006,g1p
    0.1051      1.38      0.2942      0.1133    0.258245    0.100705         HERMES,2006,g1p
    0.1054      2.29      0.2104      0.0472    0.276918     1.98609         HERMES,2006,g1p
    0.1064      3.65      0.2989      0.0396    0.290258   0.0476296         HERMES,2006,g1p
    0.1344      1.46      0.2283       0.124    0.239885   0.0087291         HERMES,2006,g1p
    0.1347      2.56      0.2724       0.043    0.256066    0.144303         HERMES,2006,g1p
    0.1358       4.3      0.2977      0.0325    0.267874    0.842211         HERMES,2006,g1p
    0.1719      1.56      0.2623      0.1396     0.21679    0.106279         HERMES,2006,g1p
    0.1722      2.87      0.2741      0.0398     0.23135     1.15376         HERMES,2006,g1p
    0.1734      5.05      0.2768      0.0274    0.241528     1.65716         HERMES,2006,g1p
    0.2191      1.67      0.2075      0.1545    0.196295  0.00525941         HERMES,2006,g1p
      0.22      3.18      0.2076      0.0367    0.208455 0.000542143         HERMES,2006,g1p
    0.2213      5.87      0.2245      0.0232    0.215707     0.14364         HERMES,2006,g1p
    0.2786      1.98      0.2548      0.1329    0.181374    0.305245         HERMES,2006,g1p
     0.281      3.77      0.1925      0.0318    0.185876   0.0433847         HERMES,2006,g1p
    0.2824      6.94      0.1936      0.0199    0.186835    0.115557         HERMES,2006,g1p
     0.355      2.46      0.1683      0.1049    0.155354   0.0152299         HERMES,2006,g1p
    0.3585      4.62      0.1576      0.0259    0.150434   0.0765616         HERMES,2006,g1p
    0.3603      8.25      0.1594      0.0171    0.145137    0.695676         HERMES,2006,g1p
     0.452      3.08       0.107      0.0808     0.10935 0.000846232         HERMES,2006,g1p
    0.4567      5.61      0.1266      0.0203   0.0997075     1.75498         HERMES,2006,g1p
    0.4589      9.72      0.1043      0.0139   0.0923907    0.734081         HERMES,2006,g1p
    0.5629       3.9       0.076      0.0578   0.0607616   0.0695057         HERMES,2006,g1p
    0.5798      6.77      0.0389      0.0164   0.0493541    0.406335         HERMES,2006,g1p
    0.5823     11.36      0.0517      0.0105   0.0440839    0.526128         HERMES,2006,g1p
    0.6921      6.32      0.0261        0.03   0.0234199  0.00798091         HERMES,2006,g1p
    0.7173      9.56      0.0257      0.0079   0.0172806     1.13581         HERMES,2006,g1p
     0.005       1.3       -0.47        0.42   -0.140633    0.614979            SMC,1998,g1d
     0.008       2.1       -0.37         0.3   -0.133612    0.620881            SMC,1998,g1d
     0.014       3.5        -0.3        0.17  -0.0943576     1.46328            SMC,1998,g1d
     0.025       5.5       -0.06        0.14  -0.0342887   0.0337282            SMC,1998,g1d
     0.035       7.5       -0.07        0.12  0.00775513    0.419851            SMC,1998,g1d
     0.049        10        0.27        0.08   0.0450538     7.90637            SMC,1998,g1d
     0.077      14.4        0.04        0.05   0.0832458    0.748079            SMC,1998,g1d
     0.121      20.6        0.09        0.04   0.0998975   0.0612248            SMC,1998,g1d
     0.172      26.8        0.15        0.03   0.0998151     2.79836            SMC,1998,g1d
     0.241      34.3        0.12        0.02   0.0938284     1.71238            SMC,1998,g1d
     0.342      43.9        0.05        0.02   0.0672058      0.7401            SMC,1998,g1d
     0.479      54.8        0.03        0.01   0.0283858    0.026058            SMC,1998,g1d
     0.024      0.51   -0.170005     0.24084           0           0           E143,1998,g1d
     0.027      0.55  -0.0589696    0.212946           0           0           E143,1998,g1d
     0.027      1.17     -0.2359    0.374186  -0.0342521    0.290411           E143,1998,g1d
     0.031      0.59   0.0563341    0.192722           0           0           E143,1998,g1d
     0.031      1.27    0.149453    0.145808  -0.0225017      1.3908           E143,1998,g1d
     0.035      0.31  -0.0578379    0.117818           0           0           E143,1998,g1d
     0.035      0.64  -0.0408655    0.168911           0           0           E143,1998,g1d
     0.035       1.4   0.0266179     0.09649  -0.0112071    0.153671           E143,1998,g1d
     0.039      0.33    0.070863    0.107307           0           0           E143,1998,g1d
     0.039      0.68    0.248898    0.150847           0           0           E143,1998,g1d
     0.039      1.52    0.189626   0.0795206 -0.00131607     5.76559           E143,1998,g1d
     0.044      0.35  0.00564536    0.101617           0           0           E143,1998,g1d
     0.044      0.73  -0.0872814    0.119438           0           0           E143,1998,g1d
     0.044      0.98    -2.31799      3.1857           0           0           E143,1998,g1d
     0.044      1.65  -0.0360562   0.0693389  0.00922998    0.426557           E143,1998,g1d
     0.049      0.36   0.0957601   0.0992423           0           0           E143,1998,g1d
     0.049      0.78    0.194798    0.110103           0           0           E143,1998,g1d
     0.049      1.06   -0.235561    0.634203   0.0120015    0.152375           E143,1998,g1d
     0.049      1.78  -0.0330221   0.0609639   0.0190625    0.729918           E143,1998,g1d
     0.056      0.38  -0.0714553   0.0936859           0           0           E143,1998,g1d
     0.056      0.57     5.26553     4.33808           0           0           E143,1998,g1d
     0.056      0.83   0.0133196    0.102751           0           0           E143,1998,g1d
     0.056      1.16     0.18558    0.312018   0.0241347    0.267727           E143,1998,g1d
     0.056      1.92   0.0362437   0.0521004   0.0310783  0.00982949           E143,1998,g1d
     0.063       0.4 -0.00876979   0.0906212           0           0           E143,1998,g1d
     0.063       0.6    0.354861    0.404638           0           0           E143,1998,g1d
     0.063      0.87   0.0846294   0.0984464           0           0           E143,1998,g1d
     0.063      1.26 -0.00742876    0.208005   0.0349294   0.0414692           E143,1998,g1d
     0.063      2.07   0.0286806   0.0471181   0.0415637   0.0747593           E143,1998,g1d
     0.063      2.69    -0.96201     4.44337   0.0449794     0.05136           E143,1998,g1d
     0.071      0.41      0.1384   0.0931539           0           0           E143,1998,g1d
     0.071      0.64   -0.105457     0.15965           0           0           E143,1998,g1d
     0.071      0.92    0.100247   0.0955477           0           0           E143,1998,g1d
     0.071      1.36    0.143126    0.159964   0.0449091    0.376988           E143,1998,g1d
     0.071      2.22   0.0461279   0.0424376   0.0508503   0.0123832           E143,1998,g1d
     0.071      2.91    0.122168    0.269544    0.054296   0.0634047           E143,1998,g1d
     0.079      0.43  -0.0172303   0.0923051           0           0           E143,1998,g1d
     0.079      0.69   0.0391998    0.105434           0           0           E143,1998,g1d
     0.079      0.97  -0.0616975   0.0946984           0           0           E143,1998,g1d
     0.079      1.47   -0.183649    0.135808   0.0521601     3.01488           E143,1998,g1d
     0.079      2.38   0.0689013    0.042013   0.0576345   0.0719179           E143,1998,g1d
     0.079      3.17  -0.0352978    0.114718   0.0611306    0.706556           E143,1998,g1d
      0.09      0.44   0.0343254   0.0863672           0           0           E143,1998,g1d
      0.09      0.74  -0.0341175   0.0755459           0           0           E143,1998,g1d
      0.09      1.01    0.141027   0.0910264   0.0550071    0.893023           E143,1998,g1d
      0.09      1.58    0.288255    0.117233   0.0584325     3.84313           E143,1998,g1d
      0.09      2.53     0.11475   0.0402369   0.0634089      1.6281           E143,1998,g1d
      0.09      3.48   0.0892463   0.0704576    0.067401   0.0961306           E143,1998,g1d
     0.101      0.45    0.159235   0.0816334           0           0           E143,1998,g1d
     0.101      0.78   0.0432137   0.0642665           0           0           E143,1998,g1d
     0.101      1.06   0.0673561   0.0894211   0.0585361  0.00972875           E143,1998,g1d
     0.101      1.69    0.122196    0.103492   0.0625428    0.332241           E143,1998,g1d
     0.101      2.69   0.0749744   0.0401649   0.0680333   0.0298653           E143,1998,g1d
     0.101      3.79   0.0941038   0.0533723   0.0725946    0.162411           E143,1998,g1d
     0.113      0.47 -0.00737882   0.0793223           0           0           E143,1998,g1d
     0.113      0.82   0.0635091   0.0574606           0           0           E143,1998,g1d
     0.113       1.1   0.0567663   0.0872518   0.0625726   0.0044285           E143,1998,g1d
     0.113       1.8   0.0586141   0.0879211   0.0667228  0.00850584           E143,1998,g1d
     0.113      2.84   0.0985826   0.0396735    0.071873    0.453246           E143,1998,g1d
     0.113      4.11   0.0365047   0.0453162   0.0767556    0.788941           E143,1998,g1d
     0.128      0.48  -0.0679933   0.0762852           0           0           E143,1998,g1d
     0.128      0.86    0.131995   0.0533405           0           0           E143,1998,g1d
     0.128      1.14    0.215743   0.0844213    0.064264     3.21959           E143,1998,g1d
     0.128      1.91   0.0371016   0.0772115   0.0687853    0.168386           E143,1998,g1d
     0.128         3    0.197567   0.0382387    0.074044     10.4349           E143,1998,g1d
     0.128      4.44   0.0852937   0.0387699   0.0792104   0.0246204           E143,1998,g1d
     0.144       0.9   0.0292598   0.0487663           0           0           E143,1998,g1d
     0.144      1.18    0.167883    0.083102   0.0634658     1.57878           E143,1998,g1d