<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE expdata [
<!ELEMENT expdata (dataset*)>
<!ATTLIST expdata
           version CDATA #IMPLIED >
<!ELEMENT dataset (ems*, point*)>
<!ATTLIST dataset
            info  CDATA #REQUIRED
            ref   CDATA #IMPLIED
            cite  CDATA #IMPLIED
            norm  CDATA #IMPLIED
            ncoef CDATA #IMPLIED
            ncerr CDATA #IMPLIED
            nstat CDATA #IMPLIED
            emid  CDATA #IMPLIED            stat  (enable|disable) #IMPLIED
 >
<!ELEMENT ems EMPTY >
<!ATTLIST ems
          emid   CDATA  #REQUIRED
          value  CDATA  #REQUIRED >
<!ELEMENT point (data*)>
<!ATTLIST point stat (fitted) #IMPLIED >
<!ELEMENT data EMPTY>
<!ATTLIST data value CDATA #REQUIRED 
               type (data|stat|syst|kine|theo|terr|scale1|scale2) #REQUIRED 
               info CDATA #REQUIRED 
               unit CDATA #IMPLIED >
]>
<expdata version="1.0" >
<dataset info="TASSO_34_1989_KApm" ref="Z. Phys.C42(1989)189" cite="Braunschweig:1988hv" stat="enable">
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0058" info="dz" unit="" />
<data type="kine" value="0.0229" info="zmax" unit="" />
<data type="kine" value="0.02" info="zmid" unit="" />
<data type="kine" value="0.0171" info="zmin" unit="" />
<data type="data" value="7.5" info="e+e-_KA" unit="" />
<data type="stat" value="0.5" info="stat" unit="" />
<data type="theo" value="18.2269" info="e+e-_KA" unit="" />
<data type="terr" value="1.11397" info="e+e-_KA" unit="" />
<data type="scale1" value="18.6874" info="e+e-_KA" unit="" />
<data type="scale2" value="17.8546" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0057" info="dz" unit="" />
<data type="kine" value="0.0286" info="zmax" unit="" />
<data type="kine" value="0.02575" info="zmid" unit="" />
<data type="kine" value="0.0229" info="zmin" unit="" />
<data type="data" value="10" info="e+e-_KA" unit="" />
<data type="stat" value="0.9" info="stat" unit="" />
<data type="theo" value="16.1889" info="e+e-_KA" unit="" />
<data type="terr" value="0.786802" info="e+e-_KA" unit="" />
<data type="scale1" value="16.5442" info="e+e-_KA" unit="" />
<data type="scale2" value="15.8885" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0057" info="dz" unit="" />
<data type="kine" value="0.0343" info="zmax" unit="" />
<data type="kine" value="0.03145" info="zmid" unit="" />
<data type="kine" value="0.0286" info="zmin" unit="" />
<data type="data" value="16.1" info="e+e-_KA" unit="" />
<data type="stat" value="1.2" info="stat" unit="" />
<data type="theo" value="14.4521" info="e+e-_KA" unit="" />
<data type="terr" value="0.682272" info="e+e-_KA" unit="" />
<data type="scale1" value="14.7301" info="e+e-_KA" unit="" />
<data type="scale2" value="14.2111" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0057" info="dz" unit="" />
<data type="kine" value="0.04" info="zmax" unit="" />
<data type="kine" value="0.03715" info="zmid" unit="" />
<data type="kine" value="0.0343" info="zmin" unit="" />
<data type="data" value="14.9" info="e+e-_KA" unit="" />
<data type="stat" value="1.7" info="stat" unit="" />
<data type="theo" value="13.0529" info="e+e-_KA" unit="" />
<data type="terr" value="0.595504" info="e+e-_KA" unit="" />
<data type="scale1" value="13.2728" info="e+e-_KA" unit="" />
<data type="scale2" value="12.8591" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0057" info="dz" unit="" />
<data type="kine" value="0.0457" info="zmax" unit="" />
<data type="kine" value="0.04285" info="zmid" unit="" />
<data type="kine" value="0.04" info="zmin" unit="" />
<data type="data" value="13.3" info="e+e-_KA" unit="" />
<data type="stat" value="3" info="stat" unit="" />
<data type="theo" value="11.8865" info="e+e-_KA" unit="" />
<data type="terr" value="0.515025" info="e+e-_KA" unit="" />
<data type="scale1" value="12.0623" info="e+e-_KA" unit="" />
<data type="scale2" value="11.7298" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0114" info="dz" unit="" />
<data type="kine" value="0.0571" info="zmax" unit="" />
<data type="kine" value="0.0514" info="zmid" unit="" />
<data type="kine" value="0.0457" info="zmin" unit="" />
<data type="data" value="12.1" info="e+e-_KA" unit="" />
<data type="stat" value="2.8" info="stat" unit="" />
<data type="theo" value="10.4759" info="e+e-_KA" unit="" />
<data type="terr" value="0.417974" info="e+e-_KA" unit="" />
<data type="scale1" value="10.6057" info="e+e-_KA" unit="" />
<data type="scale2" value="10.3587" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0343" info="dz" unit="" />
<data type="kine" value="0.0914" info="zmax" unit="" />
<data type="kine" value="0.07425" info="zmid" unit="" />
<data type="kine" value="0.0571" info="zmin" unit="" />
<data type="data" value="10.5" info="e+e-_KA" unit="" />
<data type="stat" value="2.3" info="stat" unit="" />
<data type="theo" value="7.9753" info="e+e-_KA" unit="" />
<data type="terr" value="0.261262" info="e+e-_KA" unit="" />
<data type="scale1" value="8.03623" info="e+e-_KA" unit="" />
<data type="scale2" value="7.91865" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0226" info="dz" unit="" />
<data type="kine" value="0.114" info="zmax" unit="" />
<data type="kine" value="0.1027" info="zmid" unit="" />
<data type="kine" value="0.0914" info="zmin" unit="" />
<data type="data" value="6.3" info="e+e-_KA" unit="" />
<data type="stat" value="2.8" info="stat" unit="" />
<data type="theo" value="5.94715" info="e+e-_KA" unit="" />
<data type="terr" value="0.164535" info="e+e-_KA" unit="" />
<data type="scale1" value="5.96453" info="e+e-_KA" unit="" />
<data type="scale2" value="5.92982" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.046" info="dz" unit="" />
<data type="kine" value="0.217" info="zmax" unit="" />
<data type="kine" value="0.194" info="zmid" unit="" />
<data type="kine" value="0.171" info="zmin" unit="" />
<data type="data" value="3.57" info="e+e-_KA" unit="" />
<data type="stat" value="0.61" info="stat" unit="" />
<data type="theo" value="2.86001" info="e+e-_KA" unit="" />
<data type="terr" value="0.0768564" info="e+e-_KA" unit="" />
<data type="scale1" value="2.84132" info="e+e-_KA" unit="" />
<data type="scale2" value="2.87643" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.126" info="dz" unit="" />
<data type="kine" value="0.343" info="zmax" unit="" />
<data type="kine" value="0.28" info="zmid" unit="" />
<data type="kine" value="0.217" info="zmin" unit="" />
<data type="data" value="1.75" info="e+e-_KA" unit="" />
<data type="stat" value="0.28" info="stat" unit="" />
<data type="theo" value="1.58224" info="e+e-_KA" unit="" />
<data type="terr" value="0.0415509" info="e+e-_KA" unit="" />
<data type="scale1" value="1.56217" info="e+e-_KA" unit="" />
<data type="scale2" value="1.60051" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.4" info="dz" unit="" />
<data type="kine" value="0.971" info="zmax" unit="" />
<data type="kine" value="0.771" info="zmid" unit="" />
<data type="kine" value="0.571" info="zmin" unit="" />
<data type="data" value="0.05" info="e+e-_KA" unit="" />
<data type="stat" value="0.02" info="stat" unit="" />
<data type="theo" value="0.0425031" info="e+e-_KA" unit="" />
<data type="terr" value="0.00238896" info="e+e-_KA" unit="" />
<data type="scale1" value="0.0407433" info="e+e-_KA" unit="" />
<data type="scale2" value="0.044229" info="e+e-_KA" unit="" />
</point>
</dataset>
<dataset info="TASSO_44_1989_KApm" ref="Z. Phys.C42(1989)189" cite="Braunschweig:1988hv" stat="enable">
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0046" info="dz" unit="" />
<data type="kine" value="0.0182" info="zmax" unit="" />
<data type="kine" value="0.0159" info="zmid" unit="" />
<data type="kine" value="0.0136" info="zmin" unit="" />
<data type="data" value="8.8" info="e+e-_KA" unit="" />
<data type="stat" value="1.2" info="stat" unit="" />
<data type="theo" value="21.6933" info="e+e-_KA" unit="" />
<data type="terr" value="1.55775" info="e+e-_KA" unit="" />
<data type="scale1" value="22.2326" info="e+e-_KA" unit="" />
<data type="scale2" value="21.203" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0045" info="dz" unit="" />
<data type="kine" value="0.0227" info="zmax" unit="" />
<data type="kine" value="0.02045" info="zmid" unit="" />
<data type="kine" value="0.0182" info="zmin" unit="" />
<data type="data" value="19.8" info="e+e-_KA" unit="" />
<data type="stat" value="5.3" info="stat" unit="" />
<data type="theo" value="19.6018" info="e+e-_KA" unit="" />
<data type="terr" value="1.05266" info="e+e-_KA" unit="" />
<data type="scale1" value="20.0296" info="e+e-_KA" unit="" />
<data type="scale2" value="19.202" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0046" info="dz" unit="" />
<data type="kine" value="0.0273" info="zmax" unit="" />
<data type="kine" value="0.025" info="zmid" unit="" />
<data type="kine" value="0.0227" info="zmin" unit="" />
<data type="data" value="21.3" info="e+e-_KA" unit="" />
<data type="stat" value="2.6" info="stat" unit="" />
<data type="theo" value="17.5903" info="e+e-_KA" unit="" />
<data type="terr" value="0.936742" info="e+e-_KA" unit="" />
<data type="scale1" value="17.9334" info="e+e-_KA" unit="" />
<data type="scale2" value="17.2647" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.0045" info="dz" unit="" />
<data type="kine" value="0.0318" info="zmax" unit="" />
<data type="kine" value="0.02955" info="zmid" unit="" />
<data type="kine" value="0.0273" info="zmin" unit="" />
<data type="data" value="23.3" info="e+e-_KA" unit="" />
<data type="stat" value="3.1" info="stat" unit="" />
<data type="theo" value="15.8803" info="e+e-_KA" unit="" />
<data type="terr" value="0.854521" info="e+e-_KA" unit="" />
<data type="scale1" value="16.1585" info="e+e-_KA" unit="" />
<data type="scale2" value="15.6052" info="e+e-_KA" unit="" />
</point>
</dataset>
<dataset info="TPC" ref="Phys.Rev.Lett.61(1988)1263" cite="Aihara:1988su" stat="enable">
<point >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.03" info="zmax" unit="" />
<data type="kine" value="0.0275" info="zmid" unit="" />
<data type="kine" value="0.025" info="zmin" unit="" />
<data type="data" value="5.56" info="e+e-_KA" unit="" />
<data type="stat" value="0.49" info="stat" unit="" />
<data type="theo" value="15.0973" info="e+e-_KA" unit="" />
<data type="terr" value="0.711531" info="e+e-_KA" unit="" />
<data type="scale1" value="15.4257" info="e+e-_KA" unit="" />
<data type="scale2" value="14.8205" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.035" info="zmax" unit="" />
<data type="kine" value="0.0325" info="zmid" unit="" />
<data type="kine" value="0.03" info="zmin" unit="" />
<data type="data" value="7.21" info="e+e-_KA" unit="" />
<data type="stat" value="0.56" info="stat" unit="" />
<data type="theo" value="13.757" info="e+e-_KA" unit="" />
<data type="terr" value="0.605831" info="e+e-_KA" unit="" />
<data type="scale1" value="14.0285" info="e+e-_KA" unit="" />
<data type="scale2" value="13.5224" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.04" info="zmax" unit="" />
<data type="kine" value="0.0375" info="zmid" unit="" />
<data type="kine" value="0.035" info="zmin" unit="" />
<data type="data" value="7.6" info="e+e-_KA" unit="" />
<data type="stat" value="0.59" info="stat" unit="" />
<data type="theo" value="12.6514" info="e+e-_KA" unit="" />
<data type="terr" value="0.534073" info="e+e-_KA" unit="" />
<data type="scale1" value="12.874" info="e+e-_KA" unit="" />
<data type="scale2" value="12.4561" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.045" info="zmax" unit="" />
<data type="kine" value="0.0425" info="zmid" unit="" />
<data type="kine" value="0.04" info="zmin" unit="" />
<data type="data" value="9.3" info="e+e-_KA" unit="" />
<data type="stat" value="1.2" info="stat" unit="" />
<data type="theo" value="11.6954" info="e+e-_KA" unit="" />
<data type="terr" value="0.471511" info="e+e-_KA" unit="" />
<data type="scale1" value="11.8793" info="e+e-_KA" unit="" />
<data type="scale2" value="11.5322" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.05" info="zmax" unit="" />
<data type="kine" value="0.0475" info="zmid" unit="" />
<data type="kine" value="0.045" info="zmin" unit="" />
<data type="data" value="8.55" info="e+e-_KA" unit="" />
<data type="stat" value="0.96" info="stat" unit="" />
<data type="theo" value="10.8595" info="e+e-_KA" unit="" />
<data type="terr" value="0.417429" info="e+e-_KA" unit="" />
<data type="scale1" value="11.0132" info="e+e-_KA" unit="" />
<data type="scale2" value="10.7219" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.055" info="zmax" unit="" />
<data type="kine" value="0.0525" info="zmid" unit="" />
<data type="kine" value="0.05" info="zmin" unit="" />
<data type="data" value="8.73" info="e+e-_KA" unit="" />
<data type="stat" value="0.65" info="stat" unit="" />
<data type="theo" value="10.1312" info="e+e-_KA" unit="" />
<data type="terr" value="0.372088" info="e+e-_KA" unit="" />
<data type="scale1" value="10.2606" info="e+e-_KA" unit="" />
<data type="scale2" value="10.0143" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.06" info="zmax" unit="" />
<data type="kine" value="0.0575" info="zmid" unit="" />
<data type="kine" value="0.055" info="zmin" unit="" />
<data type="data" value="8.48" info="e+e-_KA" unit="" />
<data type="stat" value="0.74" info="stat" unit="" />
<data type="theo" value="9.49457" info="e+e-_KA" unit="" />
<data type="terr" value="0.334125" info="e+e-_KA" unit="" />
<data type="scale1" value="9.6039" info="e+e-_KA" unit="" />
<data type="scale2" value="9.39505" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.065" info="zmax" unit="" />
<data type="kine" value="0.0625" info="zmid" unit="" />
<data type="kine" value="0.06" info="zmin" unit="" />
<data type="data" value="9.2" info="e+e-_KA" unit="" />
<data type="stat" value="1.3" info="stat" unit="" />
<data type="theo" value="8.93277" info="e+e-_KA" unit="" />
<data type="terr" value="0.301858" info="e+e-_KA" unit="" />
<data type="scale1" value="9.02512" info="e+e-_KA" unit="" />
<data type="scale2" value="8.84809" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.07" info="zmax" unit="" />
<data type="kine" value="0.0675" info="zmid" unit="" />
<data type="kine" value="0.065" info="zmin" unit="" />
<data type="data" value="8.8" info="e+e-_KA" unit="" />
<data type="stat" value="2.3" info="stat" unit="" />
<data type="theo" value="8.4311" info="e+e-_KA" unit="" />
<data type="terr" value="0.274039" info="e+e-_KA" unit="" />
<data type="scale1" value="8.50889" info="e+e-_KA" unit="" />
<data type="scale2" value="8.35923" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.01" info="dz" unit="" />
<data type="kine" value="0.1" info="zmax" unit="" />
<data type="kine" value="0.095" info="zmid" unit="" />
<data type="kine" value="0.09" info="zmin" unit="" />
<data type="data" value="5.6" info="e+e-_KA" unit="" />
<data type="stat" value="1.5" info="stat" unit="" />
<data type="theo" value="6.36164" info="e+e-_KA" unit="" />
<data type="terr" value="0.17631" info="e+e-_KA" unit="" />
<data type="scale1" value="6.3888" info="e+e-_KA" unit="" />
<data type="scale2" value="6.33532" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.01" info="dz" unit="" />
<data type="kine" value="0.11" info="zmax" unit="" />
<data type="kine" value="0.105" info="zmid" unit="" />
<data type="kine" value="0.1" info="zmin" unit="" />
<data type="data" value="6.32" info="e+e-_KA" unit="" />
<data type="stat" value="0.92" info="stat" unit="" />
<data type="theo" value="5.80084" info="e+e-_KA" unit="" />
<data type="terr" value="0.156712" info="e+e-_KA" unit="" />
<data type="scale1" value="5.81733" info="e+e-_KA" unit="" />
<data type="scale2" value="5.78427" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.01" info="dz" unit="" />
<data type="kine" value="0.12" info="zmax" unit="" />
<data type="kine" value="0.115" info="zmid" unit="" />
<data type="kine" value="0.11" info="zmin" unit="" />
<data type="data" value="5.13" info="e+e-_KA" unit="" />
<data type="stat" value="0.61" info="stat" unit="" />
<data type="theo" value="5.31188" info="e+e-_KA" unit="" />
<data type="terr" value="0.141868" info="e+e-_KA" unit="" />
<data type="scale1" value="5.32005" info="e+e-_KA" unit="" />
<data type="scale2" value="5.30294" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.01" info="dz" unit="" />
<data type="kine" value="0.13" info="zmax" unit="" />
<data type="kine" value="0.125" info="zmid" unit="" />
<data type="kine" value="0.12" info="zmin" unit="" />
<data type="data" value="5.13" info="e+e-_KA" unit="" />
<data type="stat" value="0.49" info="stat" unit="" />
<data type="theo" value="4.88161" info="e+e-_KA" unit="" />
<data type="terr" value="0.129949" info="e+e-_KA" unit="" />
<data type="scale1" value="4.88317" info="e+e-_KA" unit="" />
<data type="scale2" value="4.87878" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.01" info="dz" unit="" />
<data type="kine" value="0.14" info="zmax" unit="" />
<data type="kine" value="0.135" info="zmid" unit="" />
<data type="kine" value="0.13" info="zmin" unit="" />
<data type="data" value="5" info="e+e-_KA" unit="" />
<data type="stat" value="0.38" info="stat" unit="" />
<data type="theo" value="4.49941" info="e+e-_KA" unit="" />
<data type="terr" value="0.119799" info="e+e-_KA" unit="" />
<data type="scale1" value="4.49563" info="e+e-_KA" unit="" />
<data type="scale2" value="4.50155" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.05" info="dz" unit="" />
<data type="kine" value="0.3" info="zmax" unit="" />
<data type="kine" value="0.275" info="zmid" unit="" />
<data type="kine" value="0.25" info="zmin" unit="" />
<data type="data" value="1.73" info="e+e-_KA" unit="" />
<data type="stat" value="0.11" info="stat" unit="" />
<data type="theo" value="1.62322" info="e+e-_KA" unit="" />
<data type="terr" value="0.0436286" info="e+e-_KA" unit="" />
<data type="scale1" value="1.60143" info="e+e-_KA" unit="" />
<data type="scale2" value="1.64314" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.05" info="dz" unit="" />
<data type="kine" value="0.35" info="zmax" unit="" />
<data type="kine" value="0.325" info="zmid" unit="" />
<data type="kine" value="0.3" info="zmin" unit="" />
<data type="data" value="1.161" info="e+e-_KA" unit="" />
<data type="stat" value="0.073" info="stat" unit="" />
<data type="theo" value="1.14175" info="e+e-_KA" unit="" />
<data type="terr" value="0.0292548" info="e+e-_KA" unit="" />
<data type="scale1" value="1.12206" info="e+e-_KA" unit="" />
<data type="scale2" value="1.15998" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.05" info="dz" unit="" />
<data type="kine" value="0.4" info="zmax" unit="" />
<data type="kine" value="0.375" info="zmid" unit="" />
<data type="kine" value="0.35" info="zmin" unit="" />
<data type="data" value="0.842" info="e+e-_KA" unit="" />
<data type="stat" value="0.055" info="stat" unit="" />
<data type="theo" value="0.799331" info="e+e-_KA" unit="" />
<data type="terr" value="0.0204966" info="e+e-_KA" unit="" />
<data type="scale1" value="0.782535" info="e+e-_KA" unit="" />
<data type="scale2" value="0.815045" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.1" info="dz" unit="" />
<data type="kine" value="0.5" info="zmax" unit="" />
<data type="kine" value="0.45" info="zmid" unit="" />
<data type="kine" value="0.4" info="zmin" unit="" />
<data type="data" value="0.47" info="e+e-_KA" unit="" />
<data type="stat" value="0.03" info="stat" unit="" />
<data type="theo" value="0.466181" info="e+e-_KA" unit="" />
<data type="terr" value="0.0145298" info="e+e-_KA" unit="" />
<data type="scale1" value="0.453946" info="e+e-_KA" unit="" />
<data type="scale2" value="0.477788" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.1" info="dz" unit="" />
<data type="kine" value="0.6" info="zmax" unit="" />
<data type="kine" value="0.55" info="zmid" unit="" />
<data type="kine" value="0.5" info="zmin" unit="" />
<data type="data" value="0.249" info="e+e-_KA" unit="" />
<data type="stat" value="0.02" info="stat" unit="" />
<data type="theo" value="0.210988" info="e+e-_KA" unit="" />
<data type="terr" value="0.00962468" info="e+e-_KA" unit="" />
<data type="scale1" value="0.203899" info="e+e-_KA" unit="" />
<data type="scale2" value="0.217831" info="e+e-_KA" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.1" info="dz" unit="" />
<data type="kine" value="0.7" info="zmax" unit="" />
<data type="kine" value="0.65" info="zmid" unit="" />
<data type="kine" value="0.6" info="zmin" unit="" />
<data type="data" value="0.09" info="e+e-_KA" unit="" />
<data type="stat" value="0.012" info="stat" unit="" />
<data type="theo" value="0.088129" info="e+e-_KA" unit="" />
<data type="terr" value="0.00516535" info="e+e-_KA" unit="" />
<data type="scale1" value="0.0845015" info="e+e-_KA" unit="" />
<data type="scale2" value="0.0916876" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="841" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.2" info="dz" unit="" />
<data type="kine" value="0.9" info="zmax" unit="" />
<data type="kine" value="0.8" info="zmid" unit="" />
<data type="kine" value="0.7" info="zmin" unit="" />
<data type="data" value="0.0225" info="e+e-_KA" unit="" />
<data type="stat" value="0.0048" info="stat" unit="" />
<data type="theo" value="0.0216454" info="e+e-_KA" unit="" />
<data type="terr" value="0.00145065" info="e+e-_KA" unit="" />
<data type="scale1" value="0.0205081" info="e+e-_KA" unit="" />
<data type="scale2" value="0.0227862" info="e+e-_KA" unit="" />
</point>
</dataset>
<dataset info="SLD (inclusive)" ref="Phys.Rev.D59(1999)052001" norm="0.017" ncoef="-0.0438211" ncerr="0.771449" nstat="free" emid="397127-14" cite="Abe:1998zs" stat="enable">
<ems emid="0" value="9.70511e-05" />
<ems emid="1" value="-0.00476779" />
<ems emid="2" value="-0.00535692" />
<ems emid="3" value="-0.0148524" />
<ems emid="4" value="0.000103685" />
<ems emid="5" value="-0.000223458" />
<ems emid="6" value="0.000848795" />
<ems emid="7" value="7.48583e-05" />
<ems emid="8" value="-0.00215254" />
<ems emid="9" value="-0.0261242" />
<ems emid="10" value="0.000214533" />
<ems emid="11" value="-0.000887661" />
<ems emid="12" value="0.00340149" />
<ems emid="13" value="-3.79371e-06" />
<ems emid="14" value="0.595133" />
<ems emid="15" value="0.0807763" />
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.006" info="dz" unit="" />
<data type="kine" value="0.022" info="zmax" unit="" />
<data type="kine" value="0.019" info="zmid" unit="" />
<data type="kine" value="0.016" info="zmin" unit="" />
<data type="data" value="22.28" info="e+e-_KA" unit="" />
<data type="stat" value="0.47" info="stat" unit="" />
<data type="syst" value="0.53" info="syst" unit="" />
<data type="theo" value="31.2499" info="e+e-_KA" unit="" />
<data type="terr" value="2.18527" info="e+e-_KA" unit="" />
<data type="scale1" value="31.7118" info="e+e-_KA" unit="" />
<data type="scale2" value="30.7817" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.027" info="zmax" unit="" />
<data type="kine" value="0.0245" info="zmid" unit="" />
<data type="kine" value="0.022" info="zmin" unit="" />
<data type="data" value="21.22" info="e+e-_KA" unit="" />
<data type="stat" value="0.45" info="stat" unit="" />
<data type="syst" value="0.62" info="syst" unit="" />
<data type="theo" value="26.1182" info="e+e-_KA" unit="" />
<data type="terr" value="1.49214" info="e+e-_KA" unit="" />
<data type="scale1" value="26.4455" info="e+e-_KA" unit="" />
<data type="scale2" value="25.7855" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.006" info="dz" unit="" />
<data type="kine" value="0.033" info="zmax" unit="" />
<data type="kine" value="0.03" info="zmid" unit="" />
<data type="kine" value="0.027" info="zmin" unit="" />
<data type="data" value="19.1" info="e+e-_KA" unit="" />
<data type="stat" value="0.43" info="stat" unit="" />
<data type="syst" value="0.64" info="syst" unit="" />
<data type="theo" value="22.3677" info="e+e-_KA" unit="" />
<data type="terr" value="1.1033" info="e+e-_KA" unit="" />
<data type="scale1" value="22.6113" info="e+e-_KA" unit="" />
<data type="scale2" value="22.1197" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.038" info="zmax" unit="" />
<data type="kine" value="0.0355" info="zmid" unit="" />
<data type="kine" value="0.033" info="zmin" unit="" />
<data type="data" value="18.02" info="e+e-_KA" unit="" />
<data type="stat" value="0.43" info="stat" unit="" />
<data type="syst" value="0.8" info="syst" unit="" />
<data type="theo" value="19.5725" info="e+e-_KA" unit="" />
<data type="terr" value="0.842525" info="e+e-_KA" unit="" />
<data type="scale1" value="19.7566" info="e+e-_KA" unit="" />
<data type="scale2" value="19.385" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.006" info="dz" unit="" />
<data type="kine" value="0.044" info="zmax" unit="" />
<data type="kine" value="0.041" info="zmid" unit="" />
<data type="kine" value="0.038" info="zmin" unit="" />
<data type="data" value="16.45" info="e+e-_KA" unit="" />
<data type="stat" value="0.45" info="stat" unit="" />
<data type="syst" value="0.94" info="syst" unit="" />
<data type="theo" value="17.3967" info="e+e-_KA" unit="" />
<data type="terr" value="0.66451" info="e+e-_KA" unit="" />
<data type="scale1" value="17.5367" info="e+e-_KA" unit="" />
<data type="scale2" value="17.2541" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2" />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.049" info="zmax" unit="" />
<data type="kine" value="0.0465" info="zmid" unit="" />
<data type="kine" value="0.044" info="zmin" unit="" />
<data type="data" value="16.13" info="e+e-_KA" unit="" />
<data type="stat" value="0.49" info="stat" unit="" />
<data type="syst" value="1.03" info="syst" unit="" />
<data type="theo" value="15.6024" info="e+e-_KA" unit="" />
<data type="terr" value="0.534434" info="e+e-_KA" unit="" />
<data type="scale1" value="15.7099" info="e+e-_KA" unit="" />
<data type="scale2" value="15.4932" info="e+e-_KA" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2" />