<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE expdata [
<!ELEMENT expdata (dataset*)>
<!ATTLIST expdata
           version CDATA #IMPLIED >
<!ELEMENT dataset (ems*, point*)>
<!ATTLIST dataset
            info  CDATA #REQUIRED
            ref   CDATA #IMPLIED
            cite  CDATA #IMPLIED
            norm  CDATA #IMPLIED
            ncoef CDATA #IMPLIED
            ncerr CDATA #IMPLIED
            nstat CDATA #IMPLIED
            emid  CDATA #IMPLIED            stat  (enable|disable) #IMPLIED
 >
<!ELEMENT ems EMPTY >
<!ATTLIST ems
          emid   CDATA  #REQUIRED
          value  CDATA  #REQUIRED >
<!ELEMENT point (data*)>
<!ATTLIST point stat (fitted) #IMPLIED >
<!ELEMENT data EMPTY>
<!ATTLIST data value CDATA #REQUIRED 
               type (data|stat|syst|kine|theo|terr|scale1|scale2) #REQUIRED 
               info CDATA #REQUIRED 
               unit CDATA #IMPLIED >
]>
<expdata version="1.0" >
<dataset info="TASSO_34_1989_PIpm" ref="Z. Phys.C42(1989)189" norm="0.06" ncoef="-0.178592" ncerr="0.361266" nstat="free" emid="176072-19" cite="Braunschweig:1988hv" stat="enable">
<ems emid="0" value="0.000225275" />
<ems emid="1" value="0.00558481" />
<ems emid="2" value="0.00748624" />
<ems emid="3" value="-0.000109058" />
<ems emid="4" value="0.000290358" />
<ems emid="5" value="-0.000817476" />
<ems emid="6" value="-3.11166e-05" />
<ems emid="7" value="-7.28818e-06" />
<ems emid="8" value="-7.66276e-05" />
<ems emid="9" value="0.000115997" />
<ems emid="10" value="0.00148381" />
<ems emid="11" value="-5.10029e-06" />
<ems emid="12" value="-3.83607e-06" />
<ems emid="13" value="-0.000710707" />
<ems emid="14" value="-0.000828927" />
<ems emid="15" value="-0.00856668" />
<ems emid="16" value="2.19685e-05" />
<ems emid="17" value="-0.000401119" />
<ems emid="18" value="-0.00260795" />
<ems emid="19" value="0.130513" />
<ems emid="20" value="0.00625642" />
<ems emid="21" value="0.00935445" />
<ems emid="22" value="0.00563821" />
<ems emid="23" value="0.00174818" />
<ems emid="24" value="0.00609987" />
<ems emid="25" value="0.00242806" />
<ems emid="26" value="0.00242373" />
<ems emid="27" value="0.00322561" />
<ems emid="28" value="0.001083" />
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0058" info="dz" unit="" />
<data type="kine" value="0.0229" info="zmax" unit="" />
<data type="kine" value="0.02" info="zmid" unit="" />
<data type="kine" value="0.0171" info="zmin" unit="" />
<data type="data" value="162" info="e+e-_PI" unit="" />
<data type="stat" value="3" info="stat" unit="" />
<data type="theo" value="255.662" info="e+e-_PI" unit="" />
<data type="terr" value="8.77113" info="e+e-_PI" unit="" />
<data type="scale1" value="263.726" info="e+e-_PI" unit="" />
<data type="scale2" value="251.327" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0057" info="dz" unit="" />
<data type="kine" value="0.0286" info="zmax" unit="" />
<data type="kine" value="0.02575" info="zmid" unit="" />
<data type="kine" value="0.0229" info="zmin" unit="" />
<data type="data" value="151" info="e+e-_PI" unit="" />
<data type="stat" value="3" info="stat" unit="" />
<data type="theo" value="195.067" info="e+e-_PI" unit="" />
<data type="terr" value="5.95466" info="e+e-_PI" unit="" />
<data type="scale1" value="200.362" info="e+e-_PI" unit="" />
<data type="scale2" value="192.172" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0057" info="dz" unit="" />
<data type="kine" value="0.0343" info="zmax" unit="" />
<data type="kine" value="0.03145" info="zmid" unit="" />
<data type="kine" value="0.0286" info="zmin" unit="" />
<data type="data" value="129" info="e+e-_PI" unit="" />
<data type="stat" value="3" info="stat" unit="" />
<data type="theo" value="154.354" info="e+e-_PI" unit="" />
<data type="terr" value="4.3482" info="e+e-_PI" unit="" />
<data type="scale1" value="158.094" info="e+e-_PI" unit="" />
<data type="scale2" value="152.283" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0057" info="dz" unit="" />
<data type="kine" value="0.04" info="zmax" unit="" />
<data type="kine" value="0.03715" info="zmid" unit="" />
<data type="kine" value="0.0343" info="zmin" unit="" />
<data type="data" value="116" info="e+e-_PI" unit="" />
<data type="stat" value="3" info="stat" unit="" />
<data type="theo" value="126.006" info="e+e-_PI" unit="" />
<data type="terr" value="3.34536" info="e+e-_PI" unit="" />
<data type="scale1" value="128.741" info="e+e-_PI" unit="" />
<data type="scale2" value="124.475" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0057" info="dz" unit="" />
<data type="kine" value="0.0457" info="zmax" unit="" />
<data type="kine" value="0.04285" info="zmid" unit="" />
<data type="kine" value="0.04" info="zmin" unit="" />
<data type="data" value="98.9" info="e+e-_PI" unit="" />
<data type="stat" value="2.5" info="stat" unit="" />
<data type="theo" value="105.148" info="e+e-_PI" unit="" />
<data type="terr" value="2.67031" info="e+e-_PI" unit="" />
<data type="scale1" value="107.202" info="e+e-_PI" unit="" />
<data type="scale2" value="103.986" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0114" info="dz" unit="" />
<data type="kine" value="0.0571" info="zmax" unit="" />
<data type="kine" value="0.0514" info="zmid" unit="" />
<data type="kine" value="0.0457" info="zmin" unit="" />
<data type="data" value="79.8" info="e+e-_PI" unit="" />
<data type="stat" value="1.6" info="stat" unit="" />
<data type="theo" value="82.9668" info="e+e-_PI" unit="" />
<data type="terr" value="2.0067" info="e+e-_PI" unit="" />
<data type="scale1" value="84.371" info="e+e-_PI" unit="" />
<data type="scale2" value="82.1621" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0115" info="dz" unit="" />
<data type="kine" value="0.0686" info="zmax" unit="" />
<data type="kine" value="0.06285" info="zmid" unit="" />
<data type="kine" value="0.0571" info="zmin" unit="" />
<data type="data" value="59.1" info="e+e-_PI" unit="" />
<data type="stat" value="4.2" info="stat" unit="" />
<data type="theo" value="62.5844" info="e+e-_PI" unit="" />
<data type="terr" value="1.44014" info="e+e-_PI" unit="" />
<data type="scale1" value="63.46" info="e+e-_PI" unit="" />
<data type="scale2" value="62.073" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0228" info="dz" unit="" />
<data type="kine" value="0.0914" info="zmax" unit="" />
<data type="kine" value="0.08" info="zmid" unit="" />
<data type="kine" value="0.0686" info="zmin" unit="" />
<data type="data" value="43.1" info="e+e-_PI" unit="" />
<data type="stat" value="2.8" info="stat" unit="" />
<data type="theo" value="44.157" info="e+e-_PI" unit="" />
<data type="terr" value="0.971914" info="e+e-_PI" unit="" />
<data type="scale1" value="44.6233" info="e+e-_PI" unit="" />
<data type="scale2" value="43.8758" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0226" info="dz" unit="" />
<data type="kine" value="0.114" info="zmax" unit="" />
<data type="kine" value="0.1027" info="zmid" unit="" />
<data type="kine" value="0.0914" info="zmin" unit="" />
<data type="data" value="30.3" info="e+e-_PI" unit="" />
<data type="stat" value="1.7" info="stat" unit="" />
<data type="theo" value="29.5868" info="e+e-_PI" unit="" />
<data type="terr" value="0.633624" info="e+e-_PI" unit="" />
<data type="scale1" value="29.7819" info="e+e-_PI" unit="" />
<data type="scale2" value="29.4605" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.032" info="dz" unit="" />
<data type="kine" value="0.146" info="zmax" unit="" />
<data type="kine" value="0.13" info="zmid" unit="" />
<data type="kine" value="0.114" info="zmin" unit="" />
<data type="data" value="19.3" info="e+e-_PI" unit="" />
<data type="stat" value="1.1" info="stat" unit="" />
<data type="theo" value="19.721" info="e+e-_PI" unit="" />
<data type="terr" value="0.419415" info="e+e-_PI" unit="" />
<data type="scale1" value="19.7755" info="e+e-_PI" unit="" />
<data type="scale2" value="19.6772" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.023" info="dz" unit="" />
<data type="kine" value="0.194" info="zmax" unit="" />
<data type="kine" value="0.1825" info="zmid" unit="" />
<data type="kine" value="0.171" info="zmin" unit="" />
<data type="data" value="9.1" info="e+e-_PI" unit="" />
<data type="stat" value="1" info="stat" unit="" />
<data type="theo" value="10.0602" info="e+e-_PI" unit="" />
<data type="terr" value="0.216361" info="e+e-_PI" unit="" />
<data type="scale1" value="10.0229" info="e+e-_PI" unit="" />
<data type="scale2" value="10.0731" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.023" info="dz" unit="" />
<data type="kine" value="0.217" info="zmax" unit="" />
<data type="kine" value="0.2055" info="zmid" unit="" />
<data type="kine" value="0.194" info="zmin" unit="" />
<data type="data" value="7.7" info="e+e-_PI" unit="" />
<data type="stat" value="0.7" info="stat" unit="" />
<data type="theo" value="7.73966" info="e+e-_PI" unit="" />
<data type="terr" value="0.167108" info="e+e-_PI" unit="" />
<data type="scale1" value="7.69111" info="e+e-_PI" unit="" />
<data type="scale2" value="7.76043" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.046" info="dz" unit="" />
<data type="kine" value="0.263" info="zmax" unit="" />
<data type="kine" value="0.24" info="zmid" unit="" />
<data type="kine" value="0.217" info="zmin" unit="" />
<data type="data" value="5" info="e+e-_PI" unit="" />
<data type="stat" value="0.4" info="stat" unit="" />
<data type="theo" value="5.37401" info="e+e-_PI" unit="" />
<data type="terr" value="0.116532" info="e+e-_PI" unit="" />
<data type="scale1" value="5.32191" info="e+e-_PI" unit="" />
<data type="scale2" value="5.39871" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.08" info="dz" unit="" />
<data type="kine" value="0.343" info="zmax" unit="" />
<data type="kine" value="0.303" info="zmid" unit="" />
<data type="kine" value="0.263" info="zmin" unit="" />
<data type="data" value="2.85" info="e+e-_PI" unit="" />
<data type="stat" value="0.19" info="stat" unit="" />
<data type="theo" value="2.89501" info="e+e-_PI" unit="" />
<data type="terr" value="0.0644238" info="e+e-_PI" unit="" />
<data type="scale1" value="2.85156" info="e+e-_PI" unit="" />
<data type="scale2" value="2.91709" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.228" info="dz" unit="" />
<data type="kine" value="0.571" info="zmax" unit="" />
<data type="kine" value="0.457" info="zmid" unit="" />
<data type="kine" value="0.343" info="zmin" unit="" />
<data type="data" value="0.91" info="e+e-_PI" unit="" />
<data type="stat" value="0.052" info="stat" unit="" />
<data type="theo" value="0.846361" info="e+e-_PI" unit="" />
<data type="terr" value="0.0221537" info="e+e-_PI" unit="" />
<data type="scale1" value="0.826603" info="e+e-_PI" unit="" />
<data type="scale2" value="0.856949" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1156" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.4" info="dz" unit="" />
<data type="kine" value="0.971" info="zmax" unit="" />
<data type="kine" value="0.771" info="zmid" unit="" />
<data type="kine" value="0.571" info="zmin" unit="" />
<data type="data" value="0.11" info="e+e-_PI" unit="" />
<data type="stat" value="0.02" info="stat" unit="" />
<data type="theo" value="0.0848501" info="e+e-_PI" unit="" />
<data type="terr" value="0.00292831" info="e+e-_PI" unit="" />
<data type="scale1" value="0.081588" info="e+e-_PI" unit="" />
<data type="scale2" value="0.0866717" info="e+e-_PI" unit="" />
</point>
</dataset>
<dataset info="TASSO" ref="Z. Phys.C42(1989)189" norm="0.06" ncoef="-0.503983" ncerr="0.592903" nstat="free" emid="176072-20" cite="Braunschweig:1988hv" stat="enable">
<ems emid="0" value="0.000184079" />
<ems emid="1" value="0.0023465" />
<ems emid="2" value="0.0064984" />
<ems emid="3" value="-0.000105587" />
<ems emid="4" value="0.000402212" />
<ems emid="5" value="-0.000260265" />
<ems emid="6" value="-1.6006e-05" />
<ems emid="7" value="1.19195e-05" />
<ems emid="8" value="-8.26913e-05" />
<ems emid="9" value="0.00039007" />
<ems emid="10" value="0.00128466" />
<ems emid="11" value="-4.03271e-06" />
<ems emid="12" value="-5.37493e-06" />
<ems emid="13" value="-0.000543664" />
<ems emid="14" value="0.000779855" />
<ems emid="15" value="-0.00559491" />
<ems emid="16" value="3.48041e-06" />
<ems emid="17" value="-0.000240719" />
<ems emid="18" value="-0.00201477" />
<ems emid="19" value="0.00625642" />
<ems emid="20" value="0.351534" />
<ems emid="21" value="0.00710858" />
<ems emid="22" value="0.00407528" />
<ems emid="23" value="0.00130657" />
<ems emid="24" value="0.00459164" />
<ems emid="25" value="0.00155023" />
<ems emid="26" value="0.00168105" />
<ems emid="27" value="0.00272454" />
<ems emid="28" value="0.000846249" />
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0046" info="dz" unit="" />
<data type="kine" value="0.0182" info="zmax" unit="" />
<data type="kine" value="0.0159" info="zmid" unit="" />
<data type="kine" value="0.0136" info="zmin" unit="" />
<data type="data" value="202" info="e+e-_PI" unit="" />
<data type="stat" value="4" info="stat" unit="" />
<data type="theo" value="341.918" info="e+e-_PI" unit="" />
<data type="terr" value="15.6008" info="e+e-_PI" unit="" />
<data type="scale1" value="352.184" info="e+e-_PI" unit="" />
<data type="scale2" value="335.852" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0045" info="dz" unit="" />
<data type="kine" value="0.0227" info="zmax" unit="" />
<data type="kine" value="0.02045" info="zmid" unit="" />
<data type="kine" value="0.0182" info="zmin" unit="" />
<data type="data" value="188" info="e+e-_PI" unit="" />
<data type="stat" value="8" info="stat" unit="" />
<data type="theo" value="264.202" info="e+e-_PI" unit="" />
<data type="terr" value="11.2861" info="e+e-_PI" unit="" />
<data type="scale1" value="271.145" info="e+e-_PI" unit="" />
<data type="scale2" value="260.077" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0046" info="dz" unit="" />
<data type="kine" value="0.0273" info="zmax" unit="" />
<data type="kine" value="0.025" info="zmid" unit="" />
<data type="kine" value="0.0227" info="zmin" unit="" />
<data type="data" value="166" info="e+e-_PI" unit="" />
<data type="stat" value="4" info="stat" unit="" />
<data type="theo" value="211.42" info="e+e-_PI" unit="" />
<data type="terr" value="8.69168" info="e+e-_PI" unit="" />
<data type="scale1" value="216.351" info="e+e-_PI" unit="" />
<data type="scale2" value="208.473" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0045" info="dz" unit="" />
<data type="kine" value="0.0318" info="zmax" unit="" />
<data type="kine" value="0.02955" info="zmid" unit="" />
<data type="kine" value="0.0273" info="zmin" unit="" />
<data type="data" value="143" info="e+e-_PI" unit="" />
<data type="stat" value="6" info="stat" unit="" />
<data type="theo" value="173.067" info="e+e-_PI" unit="" />
<data type="terr" value="6.92905" info="e+e-_PI" unit="" />
<data type="scale1" value="176.749" info="e+e-_PI" unit="" />
<data type="scale2" value="170.856" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0181" info="dz" unit="" />
<data type="kine" value="0.0545" info="zmax" unit="" />
<data type="kine" value="0.04545" info="zmid" unit="" />
<data type="kine" value="0.0364" info="zmin" unit="" />
<data type="data" value="96.8" info="e+e-_PI" unit="" />
<data type="stat" value="11.4" info="stat" unit="" />
<data type="theo" value="101.675" info="e+e-_PI" unit="" />
<data type="terr" value="3.88364" info="e+e-_PI" unit="" />
<data type="scale1" value="103.303" info="e+e-_PI" unit="" />
<data type="scale2" value="100.685" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0182" info="dz" unit="" />
<data type="kine" value="0.0727" info="zmax" unit="" />
<data type="kine" value="0.0636" info="zmid" unit="" />
<data type="kine" value="0.0545" info="zmin" unit="" />
<data type="data" value="56.5" info="e+e-_PI" unit="" />
<data type="stat" value="6.2" info="stat" unit="" />
<data type="theo" value="62.9224" info="e+e-_PI" unit="" />
<data type="terr" value="2.34132" info="e+e-_PI" unit="" />
<data type="scale1" value="63.654" info="e+e-_PI" unit="" />
<data type="scale2" value="62.4716" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0182" info="dz" unit="" />
<data type="kine" value="0.0909" info="zmax" unit="" />
<data type="kine" value="0.0818" info="zmid" unit="" />
<data type="kine" value="0.0727" info="zmin" unit="" />
<data type="data" value="33.9" info="e+e-_PI" unit="" />
<data type="stat" value="5.1" info="stat" unit="" />
<data type="theo" value="42.8305" info="e+e-_PI" unit="" />
<data type="terr" value="1.57439" info="e+e-_PI" unit="" />
<data type="scale1" value="43.1869" info="e+e-_PI" unit="" />
<data type="scale2" value="42.6068" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.0271" info="dz" unit="" />
<data type="kine" value="0.118" info="zmax" unit="" />
<data type="kine" value="0.10445" info="zmid" unit="" />
<data type="kine" value="0.0909" info="zmin" unit="" />
<data type="data" value="25.5" info="e+e-_PI" unit="" />
<data type="stat" value="4" info="stat" unit="" />
<data type="theo" value="28.8703" info="e+e-_PI" unit="" />
<data type="terr" value="1.05576" info="e+e-_PI" unit="" />
<data type="scale1" value="29.0151" info="e+e-_PI" unit="" />
<data type="scale2" value="28.7756" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.037" info="dz" unit="" />
<data type="kine" value="0.173" info="zmax" unit="" />
<data type="kine" value="0.1545" info="zmid" unit="" />
<data type="kine" value="0.136" info="zmin" unit="" />
<data type="data" value="12.9" info="e+e-_PI" unit="" />
<data type="stat" value="2" info="stat" unit="" />
<data type="theo" value="14.075" info="e+e-_PI" unit="" />
<data type="terr" value="0.515686" info="e+e-_PI" unit="" />
<data type="scale1" value="14.0627" info="e+e-_PI" unit="" />
<data type="scale2" value="14.0778" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.1" info="dz" unit="" />
<data type="kine" value="0.273" info="zmax" unit="" />
<data type="kine" value="0.223" info="zmid" unit="" />
<data type="kine" value="0.173" info="zmin" unit="" />
<data type="data" value="6.4" info="e+e-_PI" unit="" />
<data type="stat" value="0.5" info="stat" unit="" />
<data type="theo" value="6.57649" info="e+e-_PI" unit="" />
<data type="terr" value="0.242101" info="e+e-_PI" unit="" />
<data type="scale1" value="6.53103" info="e+e-_PI" unit="" />
<data type="scale2" value="6.60152" info="e+e-_PI" unit="" />
</point>
<point stat="fitted" >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.182" info="dz" unit="" />
<data type="kine" value="0.455" info="zmax" unit="" />
<data type="kine" value="0.364" info="zmid" unit="" />
<data type="kine" value="0.273" info="zmin" unit="" />
<data type="data" value="2.1" info="e+e-_PI" unit="" />
<data type="stat" value="0.2" info="stat" unit="" />
<data type="theo" value="1.73455" info="e+e-_PI" unit="" />
<data type="terr" value="0.0658218" info="e+e-_PI" unit="" />
<data type="scale1" value="1.70603" info="e+e-_PI" unit="" />
<data type="scale2" value="1.7513" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="1936" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.545" info="dz" unit="" />
<data type="kine" value="1" info="zmax" unit="" />
<data type="kine" value="0.7275" info="zmid" unit="" />
<data type="kine" value="0.455" info="zmin" unit="" />
<data type="data" value="0.2" info="e+e-_PI" unit="" />
<data type="stat" value="0.04" info="stat" unit="" />
<data type="theo" value="0.15484" info="e+e-_PI" unit="" />
<data type="terr" value="0.00664182" info="e+e-_PI" unit="" />
<data type="scale1" value="0.150371" info="e+e-_PI" unit="" />
<data type="scale2" value="0.157546" info="e+e-_PI" unit="" />
</point>
</dataset>
<dataset info="SLD (inclusive)" ref="Phys.Rev.D59(1999)052001" norm="0.017" ncoef="-0.634974" ncerr="0.30315" nstat="free" emid="176072-21" cite="Abe:1998zs" stat="enable">
<ems emid="0" value="-0.000413011" />
<ems emid="1" value="-0.0122953" />
<ems emid="2" value="-0.0211007" />
<ems emid="3" value="-3.3002e-05" />
<ems emid="4" value="6.52701e-05" />
<ems emid="5" value="0.00149328" />
<ems emid="6" value="0.000119283" />
<ems emid="7" value="0.000390291" />
<ems emid="8" value="0.000313721" />
<ems emid="9" value="-0.00185162" />
<ems emid="10" value="-0.00644372" />
<ems emid="11" value="2.03365e-05" />
<ems emid="12" value="2.83738e-05" />
<ems emid="13" value="-9.46474e-05" />
<ems emid="14" value="0.000591233" />
<ems emid="15" value="0.0063532" />
<ems emid="16" value="3.81775e-05" />
<ems emid="17" value="0.000212393" />
<ems emid="18" value="0.001467" />
<ems emid="19" value="0.00935445" />
<ems emid="20" value="0.00710858" />
<ems emid="21" value="0.0919002" />
<ems emid="22" value="0.0179059" />
<ems emid="23" value="0.00219871" />
<ems emid="24" value="0.00717332" />
<ems emid="25" value="0.00575286" />
<ems emid="26" value="0.00685458" />
<ems emid="27" value="0.0110511" />
<ems emid="28" value="0.00821509" />
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.002" info="dz" unit="" />
<data type="kine" value="0.01" info="zmax" unit="" />
<data type="kine" value="0.009" info="zmid" unit="" />
<data type="kine" value="0.008" info="zmin" unit="" />
<data type="data" value="482.3" info="e+e-_PI" unit="" />
<data type="stat" value="2.3" info="stat" unit="" />
<data type="syst" value="7.2" info="syst" unit="" />
<data type="theo" value="817.301" info="e+e-_PI" unit="" />
<data type="terr" value="24.2124" info="e+e-_PI" unit="" />
<data type="scale1" value="836.114" info="e+e-_PI" unit="" />
<data type="scale2" value="805.437" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.002" info="dz" unit="" />
<data type="kine" value="0.012" info="zmax" unit="" />
<data type="kine" value="0.011" info="zmid" unit="" />
<data type="kine" value="0.01" info="zmin" unit="" />
<data type="data" value="439" info="e+e-_PI" unit="" />
<data type="stat" value="2.3" info="stat" unit="" />
<data type="syst" value="3.7" info="syst" unit="" />
<data type="theo" value="669.179" info="e+e-_PI" unit="" />
<data type="terr" value="16.075" info="e+e-_PI" unit="" />
<data type="scale1" value="683.444" info="e+e-_PI" unit="" />
<data type="scale2" value="660.187" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.002" info="dz" unit="" />
<data type="kine" value="0.014" info="zmax" unit="" />
<data type="kine" value="0.013" info="zmid" unit="" />
<data type="kine" value="0.012" info="zmin" unit="" />
<data type="data" value="400.5" info="e+e-_PI" unit="" />
<data type="stat" value="2" info="stat" unit="" />
<data type="syst" value="3.3" info="syst" unit="" />
<data type="theo" value="559.421" info="e+e-_PI" unit="" />
<data type="terr" value="11.3457" info="e+e-_PI" unit="" />
<data type="scale1" value="570.581" info="e+e-_PI" unit="" />
<data type="scale2" value="552.387" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.002" info="dz" unit="" />
<data type="kine" value="0.016" info="zmax" unit="" />
<data type="kine" value="0.015" info="zmid" unit="" />
<data type="kine" value="0.014" info="zmin" unit="" />
<data type="data" value="356.1" info="e+e-_PI" unit="" />
<data type="stat" value="1.9" info="stat" unit="" />
<data type="syst" value="3" info="syst" unit="" />
<data type="theo" value="476.299" info="e+e-_PI" unit="" />
<data type="terr" value="8.37936" info="e+e-_PI" unit="" />
<data type="scale1" value="485.238" info="e+e-_PI" unit="" />
<data type="scale2" value="470.664" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.006" info="dz" unit="" />
<data type="kine" value="0.022" info="zmax" unit="" />
<data type="kine" value="0.019" info="zmid" unit="" />
<data type="kine" value="0.016" info="zmin" unit="" />
<data type="data" value="292.8" info="e+e-_PI" unit="" />
<data type="stat" value="1" info="stat" unit="" />
<data type="syst" value="2.4" info="syst" unit="" />
<data type="theo" value="363.352" info="e+e-_PI" unit="" />
<data type="terr" value="5.14882" info="e+e-_PI" unit="" />
<data type="scale1" value="369.488" info="e+e-_PI" unit="" />
<data type="scale2" value="359.486" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.027" info="zmax" unit="" />
<data type="kine" value="0.0245" info="zmid" unit="" />
<data type="kine" value="0.022" info="zmin" unit="" />
<data type="data" value="228.5" info="e+e-_PI" unit="" />
<data type="stat" value="1" info="stat" unit="" />
<data type="syst" value="1.9" info="syst" unit="" />
<data type="theo" value="262.901" info="e+e-_PI" unit="" />
<data type="terr" value="2.87474" info="e+e-_PI" unit="" />
<data type="scale1" value="266.742" info="e+e-_PI" unit="" />
<data type="scale2" value="260.482" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.006" info="dz" unit="" />
<data type="kine" value="0.033" info="zmax" unit="" />
<data type="kine" value="0.03" info="zmid" unit="" />
<data type="kine" value="0.027" info="zmin" unit="" />
<data type="data" value="176.6" info="e+e-_PI" unit="" />
<data type="stat" value="0.9" info="stat" unit="" />
<data type="syst" value="1.4" info="syst" unit="" />
<data type="theo" value="200.844" info="e+e-_PI" unit="" />
<data type="terr" value="1.79694" info="e+e-_PI" unit="" />
<data type="scale1" value="203.462" info="e+e-_PI" unit="" />
<data type="scale2" value="199.196" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.038" info="zmax" unit="" />
<data type="kine" value="0.0355" info="zmid" unit="" />
<data type="kine" value="0.033" info="zmin" unit="" />
<data type="data" value="144.4" info="e+e-_PI" unit="" />
<data type="stat" value="0.8" info="stat" unit="" />
<data type="syst" value="1.2" info="syst" unit="" />
<data type="theo" value="159.054" info="e+e-_PI" unit="" />
<data type="terr" value="1.20606" info="e+e-_PI" unit="" />
<data type="scale1" value="160.9" info="e+e-_PI" unit="" />
<data type="scale2" value="157.892" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.006" info="dz" unit="" />
<data type="kine" value="0.044" info="zmax" unit="" />
<data type="kine" value="0.041" info="zmid" unit="" />
<data type="kine" value="0.038" info="zmin" unit="" />
<data type="data" value="121.7" info="e+e-_PI" unit="" />
<data type="stat" value="0.8" info="stat" unit="" />
<data type="syst" value="1.6" info="syst" unit="" />
<data type="theo" value="129.777" info="e+e-_PI" unit="" />
<data type="terr" value="0.864223" info="e+e-_PI" unit="" />
<data type="scale1" value="131.123" info="e+e-_PI" unit="" />
<data type="scale2" value="128.931" info="e+e-_PI" unit="" />
</point>
<point >
<data type="kine" value="8317.44" info="Q^2" unit="GeV^2 " />
<data type="kine" value="0.005" info="dz" unit="" />
<data type="kine" value="0.049" info="zmax" unit="" />
<data type="kine" value="0.0465" info="zmid" unit="" />
<data type="kine" value="0.044" info="zmin" unit="" />
<data type="data" value="102.5" info="e+e-_PI" unit="" />
<data type="stat" value="0.9" info="stat" unit="" />
<data type="syst" value="1.9" info="syst" unit="" />
<data type="theo" value="107.895" info="e+e-_PI" unit="" />